Repository akashic-games/akashic-cli, pull requests merged in 2019-04, with the labels that each got.

#49 remarkのバージョンを最新のものにした
  .remarkrc
  package-lock.json
  package.json
  packages/akashic-cli-commons/package-lock.json
  packages/akashic-cli-commons/package.json
  packages/akashic-cli-commons/tsconfig.json
  packages/akashic-cli-config/package-lock.json
  packages/akashic-cli-config/package.json
  packages/akashic-cli-config/tsconfig.json
  packages/akashic-cli-export-html/package-lock.json
  packages/akashic-cli-export-html/package.json
  packages/akashic-cli-export-html/src/export/tsconfig.json
  packages/akashic-cli-export-html/tsconfig.json
  packages/akashic-cli-export-zip/package-lock.json
  packages/akashic-cli-export-zip/package.json
  packages/akashic-cli-export-zip/spec/tsconfig.json
  packages/akashic-cli-export-zip/tsconfig.json
  packages/akashic-cli-init/CHANGELOG.md
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/package.json
  packages/akashic-cli-init/tsconfig.json
  packages/akashic-cli-install/package-lock.json
  packages/akashic-cli-install/package.json
  packages/akashic-cli-install/tsconfig.json
  packages/akashic-cli-modify/package-lock.json
  packages/akashic-cli-modify/package.json
  packages/akashic-cli-modify/spec/tsconfig.json
  packages/akashic-cli-modify/tsconfig.json
  packages/akashic-cli-scan/package-lock.json
  packages/akashic-cli-scan/package.json
  packages/akashic-cli-scan/spec/tsconfig.json
  packages/akashic-cli-scan/tsconfig.json
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-stat/package-lock.json
  packages/akashic-cli-stat/package.json
  packages/akashic-cli-stat/tsconfig.json
  packages/akashic-cli-uninstall/package-lock.json
  packages/akashic-cli-uninstall/package.json
  packages/akashic-cli-uninstall/spec/tsconfig.json
  packages/akashic-cli-uninstall/tsconfig.json
  packages/akashic-cli-update/package-lock.json
  packages/akashic-cli-update/package.json
  packages/akashic-cli-update/spec/tsconfig.json
  packages/akashic-cli-update/tsconfig.json
  packages/akashic-cli/package-lock.json
  packages/akashic-cli/package.json
  packages/akashic-cli/tsconfig.json
Labels: other

#52 CHANGELOGの生成方法の変更
  CHANGELOG.md
  README.md
  build/updateChangelog.js
  package-lock.json
  package.json
Labels: enhancement

#63 arguments のないコンテンツを `-A` オプションで起動するとエラーになる問題を修正
  packages/akashic-cli-serve/src/client/store/Store.ts
Labels: bug

#64 内部コンポーネントの更新
  packages/akashic-cli-export-html/package.json
  packages/akashic-cli-export-html/templates/engineFilesVersion.json
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_13.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_14.js
Labels: enhancement

#65 内部コンポーネントの更新
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/external/engineFilesV2_1_13.js
  packages/akashic-cli-serve/www/external/engineFilesV2_1_14.js
Labels: enhancement

#67 scanで一部のメッセージがおかしい問題を修正
  packages/akashic-cli-scan/src/Configuration.ts
Labels: bug

#68 fix cli init help message show config help
  packages/akashic-cli-config/src/cli.ts
Labels: bug

#69 コンテンツツリー対応
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/src/client/api/ApiClient.ts
  packages/akashic-cli-serve/src/client/operator/Operator.ts
  packages/akashic-cli-serve/src/client/operator/UiOperator.ts
  packages/akashic-cli-serve/src/client/store/CoePluginEntity.ts
  packages/akashic-cli-serve/src/client/store/LocalInstanceEntity.ts
  packages/akashic-cli-serve/src/client/store/PlayEntity.ts
  packages/akashic-cli-serve/src/client/store/PlayStore.ts
  packages/akashic-cli-serve/src/client/store/ServerInstanceEntity.ts
  packages/akashic-cli-serve/src/client/store/SessionEntity.ts
  packages/akashic-cli-serve/src/client/store/Store.ts
  packages/akashic-cli-serve/src/client/view/App.tsx
  packages/akashic-cli-serve/src/client/view/container/DevtoolContainer.tsx
  packages/akashic-cli-serve/src/client/view/container/StartupScreenContainer.tsx
  packages/akashic-cli-serve/src/client/view/molecule/InstancesDevtool.tsx
  packages/akashic-cli-serve/src/client/view/organism/StartupScreen.tsx
  packages/akashic-cli-serve/src/client/view/stories/Devtool.stories.tsx
  packages/akashic-cli-serve/src/client/view/stories/StartupScreen.stories.tsx
  packages/akashic-cli-serve/src/common/types/TestbedEvent.ts
  packages/akashic-cli-serve/src/server/controller/PlayTokenController.ts
  packages/akashic-cli-serve/src/server/controller/RunnerController.ts
  packages/akashic-cli-serve/src/server/domain/PlayStore.ts
  packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
  packages/akashic-cli-serve/src/server/domain/SocketIOAMFlowManager.ts
  packages/akashic-cli-serve/src/server/index.ts
Labels: enhancement

#72 Add a button that takes over start argument and creates new play
  packages/akashic-cli-serve/src/client/operator/Operator.ts
  packages/akashic-cli-serve/src/client/view/container/ToolbarContainer.tsx
  packages/akashic-cli-serve/src/client/view/molecule/PlayControl.tsx
Labels: enhancement
