Repository akashic-games/akashic-cli, pull requests merged in 2019-07, with the labels that each got.

#94 何も変更を加えずにpublishするnpm-scriptを追加
  build/prepareRepublish.js
  build/updateChangelog.js
  package-lock.json
  package.json
Labels: other

#101 akashic-cli-initにユーザー入力をスキップするオプションを追加+publish後に動作確認するためのスクリプトを作成
  package-lock.json
  package.json
  packages/akashic-cli-init/src/BasicParameters.ts
  packages/akashic-cli-init/src/InitParameterObject.ts
  packages/akashic-cli-init/src/cli.ts
  packages/akashic-cli-init/src/init.ts
  packages/akashic-cli-serve/src/client/store/Store.ts
  test/testAfterPublish.js
Labels: enhancement, other

#119 【akashic-cli-export-html】内部コンポーネントの更新(engineFiles@2.1.21、engineFiles@1.1.9)
  packages/akashic-cli-export-html/package.json
  packages/akashic-cli-export-html/templates/engineFilesVersion.json
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_19.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_21.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/game-storage.strip.js
Labels: enhancement

#120 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@2.1.21、engineFiles@1.1.9)
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/external/akashic-gameview-web.strip.js
  packages/akashic-cli-serve/www/external/engineFilesV2_1_19.js
  packages/akashic-cli-serve/www/external/engineFilesV2_1_21.js
Labels: enhancement

#121 akashic-cli-serveに依存しているamflowとplaylogのバージョンを前のものに戻す対応
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
Labels: bug, dependencies

#123 【akashic-cli-export-html】内部コンポーネントの更新(engineFiles@2.1.21、engineFiles@1.1.10)
  packages/akashic-cli-export-html/templates/engineFilesVersion.json
  packages/akashic-cli-export-html/templates/template-export-html-v1/js/engineFilesV1_1_10.js
  packages/akashic-cli-export-html/templates/template-export-html-v1/js/engineFilesV1_1_9.js
  packages/akashic-cli-export-html/templates/template-export-html-v1/js/game-storage.strip.js
Labels: enhancement
