Repository akashic-games/akashic-cli, pull requests merged in 2019-05, with the labels that each got.

#76 akashic-cli-serveで背景画像を表示する機能を追加
  packages/akashic-cli-serve/src/client/operator/UiOperator.ts
  packages/akashic-cli-serve/src/client/store/ToolBarUiStore.ts
  packages/akashic-cli-serve/src/client/store/storage.ts
  packages/akashic-cli-serve/src/client/view/App.css
  packages/akashic-cli-serve/src/client/view/App.tsx
  packages/akashic-cli-serve/src/client/view/container/ToolbarContainer.tsx
  packages/akashic-cli-serve/src/client/view/organism/ToolBar.tsx
  packages/akashic-cli-serve/src/client/view/stories/ToolBar.stories.tsx
  packages/akashic-cli-serve/src/common/types/SandboxConfig.ts
Labels: enhancement

#80 exportを行ったツールのexport実行時のバージョンとオプションが表示されるようにする対応
  packages/akashic-cli-commons/package-lock.json
  packages/akashic-cli-commons/src/GameConfiguration.ts
  packages/akashic-cli-commons/src/index.ts
  packages/akashic-cli-export-html/src/app/cli.ts
  packages/akashic-cli-export-html/src/app/convertBundle.ts
  packages/akashic-cli-export-html/src/app/convertNoBundle.ts
  packages/akashic-cli-export-html/src/app/convertUtil.ts
  packages/akashic-cli-export-html/src/app/exportHTML.ts
  packages/akashic-cli-export-html/templates/bundle-index.ect
  packages/akashic-cli-export-html/templates/no-bundle-index.ect
  packages/akashic-cli-export-zip/src/cli.ts
  packages/akashic-cli-export-zip/src/convert.ts
  packages/akashic-cli-export-zip/src/exportZip.ts
Labels: enhancement

#81 remarkのプリセットとして@akashic/remark-preset-lintを使うよう変更
  .remarkrc
  package-lock.json
  package.json
  packages/akashic-cli-commons/package.json
  packages/akashic-cli-config/package.json
  packages/akashic-cli-export-html/package.json
  packages/akashic-cli-export-zip/package.json
  packages/akashic-cli-init/package.json
  packages/akashic-cli-install/package.json
  packages/akashic-cli-modify/package.json
  packages/akashic-cli-scan/package.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-stat/package.json
  packages/akashic-cli-uninstall/package.json
  packages/akashic-cli-update/package.json
  packages/akashic-cli/package.json
Labels: other

#77 新市場コンテンツ用のテンプレートを新規作成+akashic init実行時に一部ファイルを取得できない不具合の修正
  packages/akashic-cli-init/README.md
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/package.json
  packages/akashic-cli-init/spec/downloadTemplateSpec.js
  packages/akashic-cli-init/templates-src/javascript-shin-ichiba-ranking/.eslintrc.json
  packages/akashic-cli-init/templates-src/javascript-shin-ichiba-ranking/README.md
  packages/akashic-cli-init/templates-src/javascript-shin-ichiba-ranking/audio/se.aac
  packages/akashic-cli-init/templates-src/javascript-shin-ichiba-ranking/audio/se.ogg
  packages/akashic-cli-init/templates-src/javascript-shin-ichiba-ranking/game.json
  packages/akashic-cli-init/templates-src/javascript-shin-ichiba-ranking/image/player.png
  packages/akashic-cli-init/templates-src/javascript-shin-ichiba-ranking/image/shot.png
  packages/akashic-cli-init/templates-src/javascript-shin-ichiba-ranking/package.json
  packages/akashic-cli-init/templates-src/javascript-shin-ichiba-ranking/script/_bootstrap.js
  packages/akashic-cli-init/templates-src/javascript-shin-ichiba-ranking/script/main.js
  packages/akashic-cli-init/templates-src/javascript-shin-ichiba-ranking/text/.gitkeep
  packages/akashic-cli-init/templates/template-list.json
Labels: bug, documentation, enhancement

#82 akashic-cli-xxxモジュールのテストフレームワークをjestに変更
  packages/akashic-cli-export-html/jest.config.js
  packages/akashic-cli-export-html/package-lock.json
  packages/akashic-cli-export-html/package.json
  packages/akashic-cli-export-html/spec/exportHTMLSpec.js
  packages/akashic-cli-export-html/spec/support/jasmine.json
  packages/akashic-cli-init/jest.config.js
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/package.json
  packages/akashic-cli-init/spec/copyTemplateSpec.js
  packages/akashic-cli-init/spec/support/jasmine.json
  packages/akashic-cli-stat/jest.config.js
  packages/akashic-cli-stat/package-lock.json
  packages/akashic-cli-stat/package.json
  packages/akashic-cli-stat/spec/support/jasmine.json
  packages/akashic-cli-update/jest.config.js
  packages/akashic-cli-update/package-lock.json
  packages/akashic-cli-update/package.json
  packages/akashic-cli-update/spec/support/jasmine.json
  packages/akashic-cli/package-lock.json
  packages/akashic-cli/package.json
Labels: other

#79 akashic-cli-initのテンプレートディレクトリを生成できるようにした
  packages/akashic-cli-init/.gitignore
  packages/akashic-cli-init/README.md
  packages/akashic-cli-init/build/generateTemplateSource.js
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/package.json
  packages/akashic-cli-init/spec/downloadTemplateSpec.js
  packages/akashic-cli-init/templates-src/game-default/audio/se.aac
  packages/akashic-cli-init/templates-src/game-default/audio/se.ogg
  packages/akashic-cli-init/templates-src/game-default/game.json
  packages/akashic-cli-init/templates-src/game-default/image/player.png
  packages/akashic-cli-init/templates-src/game-default/image/shot.png
  packages/akashic-cli-init/templates-src/game-default/src/main.ts
  packages/akashic-cli-init/templates-src/game-default/text/.gitkeep
  packages/akashic-cli-init/templates-src/game-minimal/audio/.gitkeep
  packages/akashic-cli-init/templates-src/game-minimal/game.json
  packages/akashic-cli-init/templates-src/game-minimal/image/.gitkeep
  packages/akashic-cli-init/templates-src/game-minimal/src/main.ts
  packages/akashic-cli-init/templates-src/game-minimal/text/.gitkeep
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/audio/se.aac
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/audio/se.ogg
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/game.json
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/image/player.png
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/image/shot.png
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/_bootstrap.ts
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/main.ts
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/parameterObject.ts
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/text/.gitkeep
  packages/akashic-cli-init/templates-src/javascript-base/.eslintrc.json
  packages/akashic-cli-init/templates-src/javascript-base/README.md
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/javascript-minimal/README.md
  packages/akashic-cli-init/templates-src/javascript-minimal/game.json
  packages/akashic-cli-init/templates-src/javascript-minimal/package.json
  packages/akashic-cli-init/templates-src/javascript-minimal/script/main.js
  packages/akashic-cli-init/templates-src/javascript-shin-ichiba-ranking/.eslintrc.json
  packages/akashic-cli-init/templates-src/javascript/.eslintrc.json
  packages/akashic-cli-init/templates-src/javascript/README.md
  packages/akashic-cli-init/templates-src/javascript/package.json
  packages/akashic-cli-init/templates-src/typescript-base/.gitignore
  packages/akashic-cli-init/templates-src/typescript-base/README.md
  packages/akashic-cli-init/templates-src/typescript-base/jest.config.js
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/spec/helpers/.gitkeep
  packages/akashic-cli-init/templates-src/typescript-base/spec/testSpec.js
  packages/akashic-cli-init/templates-src/typescript-base/template.json
  packages/akashic-cli-init/templates-src/typescript-base/tsconfig.json
  packages/akashic-cli-init/templates-src/typescript-base/tslint.json
  packages/akashic-cli-init/templates-src/typescript/image/.gitkeep
  packages/akashic-cli-init/templates-src/typescript/spec/helpers/.gitkeep
  packages/akashic-cli-init/templates-src/typescript/text/.gitkeep
  packages/akashic-cli-init/templates/template-list.json
Labels: breaking, documentation, enhancement

#85 Fix broken publish v1.5.31 (with ignorable changes)
  packages/akashic-cli-export-html/README.md
  packages/akashic-cli-init/README.md
  packages/akashic-cli-stat/README.md
  packages/akashic-cli-update/README.md
  packages/akashic-cli/README.md
Labels: other
