Repository akashic-games/akashic-cli, pull requests merged in 2019-11, with the labels that each got.

#184 【akashic-cli-export-html】内部コンポーネントの更新(engineFiles@2.1.31, engineFiles@1.1.12)
  packages/akashic-cli-export-html/package.json
  packages/akashic-cli-export-html/templates/engineFilesVersion.json
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_30.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_31.js
Labels: enhancement

#185 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@2.1.31、engineFiles@1.1.12)
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/engineFilesV2_1_30.js
  packages/akashic-cli-serve/www/public/external/engineFilesV2_1_31.js
Labels: enhancement

#182 refactor: Refactor functions with names toggle
  packages/akashic-cli-serve/src/client/operator/UiOperator.ts
  packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
  packages/akashic-cli-serve/src/client/store/ToolBarUiStore.ts
  packages/akashic-cli-serve/src/client/view/container/DevtoolContainer.tsx
  packages/akashic-cli-serve/src/client/view/container/ToolbarContainer.tsx
  packages/akashic-cli-serve/src/client/view/molecule/DisplayOptionControl.tsx
  packages/akashic-cli-serve/src/client/view/molecule/EventsDevtool.tsx
  packages/akashic-cli-serve/src/client/view/organism/ToolBar.tsx
  packages/akashic-cli-serve/src/client/view/stories/Devtool.stories.tsx
  packages/akashic-cli-serve/src/client/view/stories/EventsDevtool.stories.tsx
  packages/akashic-cli-serve/src/client/view/stories/ToolBar.stories.tsx
Labels: other

#191 【akashic-cli-export-html】内部コンポーネントの更新(engineFiles@2.1.32, engineFiles@1.1.13)
  packages/akashic-cli-export-html/templates/engineFilesVersion.json
  packages/akashic-cli-export-html/templates/template-export-html-v1/js/engineFilesV1_1_12.js
  packages/akashic-cli-export-html/templates/template-export-html-v1/js/engineFilesV1_1_13.js
Labels: enhancement

#192 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@2.1.32、engineFiles@1.1.13)
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/engineFilesV1_1_12.js
  packages/akashic-cli-serve/www/public/external/engineFilesV1_1_13.js
Labels: enhancement

#186 fix: server stopped to contents error
  packages/akashic-cli-serve/src/client/operator/Operator.ts
  packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
Labels: bug

#190 other: replace deprecated module ect to ejs
  packages/akashic-cli-export-html/package-lock.json
  packages/akashic-cli-export-html/package.json
  packages/akashic-cli-export-html/src/app/convertBundle.ts
  packages/akashic-cli-export-html/src/app/convertNoBundle.ts
  packages/akashic-cli-export-html/templates/bundle-index.ejs
  packages/akashic-cli-export-html/templates/no-bundle-index.ejs
  packages/akashic-cli-export-html/tsconfig.json
  packages/akashic-cli-export-html/typings/ect.d.ts
Labels: other

#189 other: replace musicmetadata to music-metadata
  packages/akashic-cli-scan/package-lock.json
  packages/akashic-cli-scan/package.json
  packages/akashic-cli-scan/spec/tsconfig.json
  packages/akashic-cli-scan/src/getAudioDuration.ts
  packages/akashic-cli-scan/tsconfig.json
Labels: other

#183 specify scan dirs, asset extension
  packages/akashic-cli-scan/spec/src/ConfigurationSpec.ts
  packages/akashic-cli-scan/src/Configuration.ts
  packages/akashic-cli-scan/src/cli.ts
  packages/akashic-cli-scan/src/scan.ts
Labels: enhancement

#195 Add a command to rescan Asset IDs
  .travis.yml
  packages/akashic-cli-scan/package-lock.json
  packages/akashic-cli-scan/spec/src/ConfigurationSpec.ts
  packages/akashic-cli-scan/src/Configuration.ts
  packages/akashic-cli-scan/src/cli.ts
  packages/akashic-cli-scan/src/scan.ts
Labels: enhancement

#197 Add a command to scan assets with the file extensions
  packages/akashic-cli-scan/spec/src/ConfigurationSpec.ts
  packages/akashic-cli-scan/src/Configuration.ts
  packages/akashic-cli-scan/src/cli.ts
  packages/akashic-cli-scan/src/scan.ts
Labels: enhancement

#198 eslint js files
  packages/akashic-cli-export-html/.eslintrc.js
  packages/akashic-cli-export-html/package-lock.json
  packages/akashic-cli-export-html/package.json
  packages/akashic-cli-export-html/templates/template-export-html-v1/js/sandbox.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/sandbox.js
Labels: bug

#199 fix init --yes option
  packages/akashic-cli-init/build/generateTemplateSource.js
  packages/akashic-cli-init/src/cli.ts
Labels: bug
