Repository akashic-games/akashic-cli, pull requests merged in 2019-06, with the labels that each got.

#84 akashic-cli-initのテンプレートディレクトリを生成できるようにした
  packages/akashic-cli-init/.gitignore
  packages/akashic-cli-init/README.md
  packages/akashic-cli-init/build/generateTemplateSource.js
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/package.json
  packages/akashic-cli-init/spec/downloadTemplateSpec.js
  packages/akashic-cli-init/templates-src/game-default/audio/se.aac
  packages/akashic-cli-init/templates-src/game-default/audio/se.ogg
  packages/akashic-cli-init/templates-src/game-default/game.json
  packages/akashic-cli-init/templates-src/game-default/image/player.png
  packages/akashic-cli-init/templates-src/game-default/image/shot.png
  packages/akashic-cli-init/templates-src/game-default/src/main.ts
  packages/akashic-cli-init/templates-src/game-default/text/.gitkeep
  packages/akashic-cli-init/templates-src/game-minimal/audio/.gitkeep
  packages/akashic-cli-init/templates-src/game-minimal/game.json
  packages/akashic-cli-init/templates-src/game-minimal/image/.gitkeep
  packages/akashic-cli-init/templates-src/game-minimal/src/main.ts
  packages/akashic-cli-init/templates-src/game-minimal/text/.gitkeep
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/audio/se.aac
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/audio/se.ogg
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/game.json
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/image/player.png
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/image/shot.png
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/_bootstrap.ts
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/main.ts
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/parameterObject.ts
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/text/.gitkeep
  packages/akashic-cli-init/templates-src/javascript-base/.eslintrc.json
  packages/akashic-cli-init/templates-src/javascript-base/README.md
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/javascript-minimal/README.md
  packages/akashic-cli-init/templates-src/javascript-minimal/game.json
  packages/akashic-cli-init/templates-src/javascript-minimal/package.json
  packages/akashic-cli-init/templates-src/javascript-minimal/script/main.js
  packages/akashic-cli-init/templates-src/javascript-shin-ichiba-ranking/.eslintrc.json
  packages/akashic-cli-init/templates-src/javascript/.eslintrc.json
  packages/akashic-cli-init/templates-src/javascript/README.md
  packages/akashic-cli-init/templates-src/javascript/package.json
  packages/akashic-cli-init/templates-src/typescript-base/.gitignore
  packages/akashic-cli-init/templates-src/typescript-base/README.md
  packages/akashic-cli-init/templates-src/typescript-base/jest.config.js
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/spec/helpers/.gitkeep
  packages/akashic-cli-init/templates-src/typescript-base/spec/testSpec.js
  packages/akashic-cli-init/templates-src/typescript-base/template.json
  packages/akashic-cli-init/templates-src/typescript-base/tsconfig.json
  packages/akashic-cli-init/templates-src/typescript-base/tslint.json
  packages/akashic-cli-init/templates-src/typescript/image/.gitkeep
  packages/akashic-cli-init/templates-src/typescript/spec/helpers/.gitkeep
  packages/akashic-cli-init/templates-src/typescript/text/.gitkeep
  packages/akashic-cli-init/templates/template-list.json
Labels: breaking, documentation, enhancement

#86 initのnode12対応
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/package.json
  packages/akashic-cli-init/src/downloadTemplate.ts
  packages/akashic-cli-init/tsconfig.json
  packages/akashic-cli-init/typings/unzip.d.ts
Labels: bug

#92 Follow headless-driver@0.4.3
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/src/server/controller/PlayController.ts
  packages/akashic-cli-serve/src/server/domain/PlayStore.ts
Labels: enhancement

#97 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@2.1.19、engineFiles@1.1.9)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#98 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@2.1.19、engineFiles@1.1.9)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#91 akashic-cli-commonsとakashic-cli-configのテストフレームワークをjestに変更
  packages/akashic-cli-commons/jest.config.js
  packages/akashic-cli-commons/package-lock.json
  packages/akashic-cli-commons/package.json
  packages/akashic-cli-commons/spec/ConfigurationFileSpec.js
  packages/akashic-cli-commons/spec/ConfigurationSpec.js
  packages/akashic-cli-commons/spec/ConsoleLoggerSpec.js
  packages/akashic-cli-commons/spec/NodeModulesSpec.js
  packages/akashic-cli-commons/spec/RenamerSpec.js
  packages/akashic-cli-config/jest.config.js
  packages/akashic-cli-config/package-lock.json
  packages/akashic-cli-config/package.json
  packages/akashic-cli-config/spec/configSpec.js
Labels: other

#96 akashic-cli-initのjavascriptテンプレートの.eslintrc.jsonの修正
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/templates-src/javascript-base/.eslintrc.json
Labels: enhancement

#100 refactor: introduce ContentLocator
  packages/akashic-cli-serve/spec/server/SocketIOAMFlowManagerSpec.js
  packages/akashic-cli-serve/src/client/akashic/GameViewManager.ts
  packages/akashic-cli-serve/src/client/api/ApiClient.ts
  packages/akashic-cli-serve/src/client/api/ApiRequest.ts
  packages/akashic-cli-serve/src/client/bootstrap.tsx
  packages/akashic-cli-serve/src/client/common/ClientContentLocator.ts
  packages/akashic-cli-serve/src/client/operator/Operator.ts
  packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
  packages/akashic-cli-serve/src/client/store/LocalInstanceEntity.ts
  packages/akashic-cli-serve/src/client/store/PlayEntity.ts
  packages/akashic-cli-serve/src/client/store/PlayStore.ts
  packages/akashic-cli-serve/src/client/store/Store.ts
  packages/akashic-cli-serve/src/common/ContentLocator.ts
  packages/akashic-cli-serve/src/common/types/ApiResponse.ts
  packages/akashic-cli-serve/src/common/types/ContentLocatorData.ts
  packages/akashic-cli-serve/src/common/types/TestbedEvent.ts
  packages/akashic-cli-serve/src/server/common/ServerContentLocator.ts
  packages/akashic-cli-serve/src/server/controller/PlayController.ts
  packages/akashic-cli-serve/src/server/domain/PlayStore.ts
Labels: other

#104 majorバージョンアップをrenovateの対象外にする対応
  renovate.json
Labels: other

#102 Enable "use strict" and Add Notification component
  packages/akashic-cli-serve/src/client/operator/UiOperator.ts
  packages/akashic-cli-serve/src/client/store/NotificationType.ts
  packages/akashic-cli-serve/src/client/store/NotificationUiStore.ts
  packages/akashic-cli-serve/src/client/store/Store.ts
  packages/akashic-cli-serve/src/client/view/App.tsx
  packages/akashic-cli-serve/src/client/view/atom/Notification.css
  packages/akashic-cli-serve/src/client/view/atom/Notification.tsx
  packages/akashic-cli-serve/src/client/view/container/NotificationContainer.tsx
  packages/akashic-cli-serve/src/server/controller/ScriptAssetController.ts
Labels: breaking, enhancement

#109 export-htmlでatsumaruオプション実行時もgame.jsonにexport-zip実行時の情報が出力されるようにする
  packages/akashic-cli-export-zip/package-lock.json
  packages/akashic-cli-export-zip/src/exportZip.ts
Labels: enhancement

#110 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@2.1.19、engineFiles@1.1.9)
  packages/akashic-cli-serve/package.json
Labels: enhancement
