Repository akashic-games/akashic-cli, pull requests merged in 2020-11, with the labels that each got.

#577 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal-v3.zip
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript-v3.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal-v3.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript-v3.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#561 add save playlog button in akashic-cli-serve
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
  packages/akashic-cli-serve/src/client/view/container/DevtoolContainer.tsx
  packages/akashic-cli-serve/src/client/view/molecule/MiscDevtool.tsx
  packages/akashic-cli-serve/src/client/view/organism/Devtool.tsx
  packages/akashic-cli-serve/src/client/view/stories/Devtool.stories.tsx
Labels: enhancement

#579 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal-v3.zip
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript-v3.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal-v3.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript-v3.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#580 fix: Invalid node version
  .github/workflows/test.yml
Labels: other

#552 add watch option in akashic-cli-scan
  packages/akashic-cli-commons/src/CliConfig/CliConfigScan.ts
  packages/akashic-cli-scan/package-lock.json
  packages/akashic-cli-scan/package.json
  packages/akashic-cli-scan/spec/src/ConfigurationSpec.ts
  packages/akashic-cli-scan/src/Configuration.ts
  packages/akashic-cli-scan/src/cli.ts
  packages/akashic-cli-scan/src/scan.ts
Labels: enhancement

#581 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal-v3.zip
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript-v3.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal-v3.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript-v3.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#583 【akashic-cli-export-html】内部コンポーネントの更新(engineFiles@3.0.0-beta.10, engineFiles@2.1.48, engineFiles@1.1.16)
  packages/akashic-cli-export-html/package.json
  packages/akashic-cli-export-html/templates/engineFilesVersion.json
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_47.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_48.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/game-storage.strip.js
Labels: enhancement

#584 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.0-beta.10, engineFiles@2.1.48, engineFiles@1.1.16)
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/engineFilesV2_1_47.js
  packages/akashic-cli-serve/www/public/external/engineFilesV2_1_48.js
Labels: enhancement

#585 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal-v3.zip
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript-v3.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal-v3.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript-v3.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#586 【akashic-cli-export-html】内部コンポーネントの更新(engineFiles@3.0.0-beta.11, engineFiles@2.1.48, engineFiles@1.1.16)
  packages/akashic-cli-export-html/templates/engineFilesVersion.json
  packages/akashic-cli-export-html/templates/template-export-html-v3/js/engineFilesV3_0_0_beta_10.js
  packages/akashic-cli-export-html/templates/template-export-html-v3/js/engineFilesV3_0_0_beta_11.js
  packages/akashic-cli-export-html/templates/template-export-html-v3/js/game-storage.strip.js
Labels: enhancement

#587 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/javascript-base/package.json
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal-v3.zip
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript-v3.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal-v3.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript-v3.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#582 fix npm-scripts about generating zips
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/package.json
  packages/akashic-cli-init/templates/javascript-minimal-v3.zip
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript-v3.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal-v3.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript-v3.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: bug

#588 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.0-beta.11, engineFiles@2.1.48, engineFiles@1.1.16)
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/engineFilesV3_0_0_beta_10.js
  packages/akashic-cli-serve/www/public/external/engineFilesV3_0_0_beta_11.js
Labels: enhancement

#595 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/javascript-base/package.json
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal-v3.zip
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript-v3.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal-v3.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript-v3.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#597 feat(serve): update @akashic/headless-driver to 1.5.0
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
Labels: dependencies

#592 stop to depend on game-storage
  packages/akashic-cli-export-html/.eslintignore
  packages/akashic-cli-export-html/.eslintrc.js
  packages/akashic-cli-export-html/build-template-support/checkAkashicVersions.js
  packages/akashic-cli-export-html/build-template-support/generateAkashicVersionsFile.js
  packages/akashic-cli-export-html/build-template-support/updatefiles.js
  packages/akashic-cli-export-html/package-lock.json
  packages/akashic-cli-export-html/package.json
  packages/akashic-cli-export-html/src/app/convertUtil.ts
  packages/akashic-cli-export-html/templates/no-bundle-index.ejs
  packages/akashic-cli-export-html/templates/template-export-html-v1/js/game-storage.strip.js
  packages/akashic-cli-export-html/templates/template-export-html-v1/js/sandbox.js
  packages/akashic-cli-export-html/templates/template-export-html-v1/js/versions.json
  packages/akashic-cli-export-html/templates/template-export-html-v1/package.json
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/game-storage.strip.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/sandbox.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/versions.json
  packages/akashic-cli-export-html/templates/template-export-html-v2/package.json
  packages/akashic-cli-export-html/templates/template-export-html-v3/js/game-storage.strip.js
  packages/akashic-cli-export-html/templates/template-export-html-v3/js/sandbox.js
  packages/akashic-cli-export-html/templates/template-export-html-v3/js/versions.json
  packages/akashic-cli-export-html/templates/template-export-html-v3/package.json
Labels: other

#601 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal-v3.zip
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript-v3.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal-v3.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript-v3.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#602 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/javascript-base/package.json
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal-v3.zip
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript-v3.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal-v3.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript-v3.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#590 Change game size in init template
  packages/akashic-cli-init/templates-src-v3/game-default/game.json
  packages/akashic-cli-init/templates-src-v3/game-minimal/game.json
  packages/akashic-cli-init/templates-src-v3/game-shin-ichiba-ranking/game.json
  packages/akashic-cli-init/templates-src/game-default/game.json
  packages/akashic-cli-init/templates-src/game-minimal/game.json
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/game.json
  packages/akashic-cli-init/templates/javascript-minimal-v3.zip
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript-v3.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal-v3.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript-v3.zip
  packages/akashic-cli-init/templates/typescript.zip
  packages/akashic-cli-scan/spec/src/ConfigurationSpec.ts
  packages/akashic-cli-scan/src/Configuration.ts
Labels: other

#598 reconnection when server restart
  packages/akashic-cli-serve/src/client/api/Subscriber.ts
  packages/akashic-cli-serve/src/client/api/socketInstance.ts
Labels: enhancement

#604 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal-v3.zip
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript-v3.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal-v3.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking-v3.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript-v3.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement
