Repository akashic-games/akashic-cli, pull requests merged in 2020-04, with the labels that each got.

#274 Set modulePathIgnorePatterns for jest.config.js
  packages/akashic-cli-export-zip/jest.config.js
  packages/akashic-cli-export-zip/spec/fixtures/simple_game_using_external/package.json
  packages/akashic-cli-export-zip/spec/fixtures/simple_game_with_aez_bundle_main/package.json
  packages/akashic-cli-export-zip/spec/fixtures/simple_game_with_aez_bundle_main2/package.json
  packages/akashic-cli-export-zip/spec/fixtures/simple_game_with_aez_bundle_main3/package.json
  packages/akashic-cli-export-zip/spec/fixtures/simple_game_with_main_scene/package.json
  packages/akashic-cli-init/jest.config.js
  packages/akashic-cli-init/templates-src-v3/javascript-base/package.json
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
Labels: other

#278 fix to work v1 content
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
Labels: bug

#279 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.0-beta.2, engineFiles@2.1.38, engineFiles@1.1.14)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#280 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#284 【akashic-cli-export-html】内部コンポーネントの更新(engineFiles@3.0.0-beta.3, engineFiles@2.1.38, engineFiles@1.1.14)
  packages/akashic-cli-export-html/package.json
  packages/akashic-cli-export-html/templates/engineFilesVersion.json
  packages/akashic-cli-export-html/templates/template-export-html-v3/js/engineFilesV3_0_0_beta_2.js
  packages/akashic-cli-export-html/templates/template-export-html-v3/js/engineFilesV3_0_0_beta_3.js
Labels: enhancement

#285 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#286 【akashic-cli-export-html】内部コンポーネントの更新(engineFiles@3.0.0-beta.3, engineFiles@2.1.39, engineFiles@1.1.14)
  packages/akashic-cli-export-html/package.json
  packages/akashic-cli-export-html/templates/engineFilesVersion.json
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_38.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_39.js
Labels: enhancement

#288 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#289 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.0-beta.3, engineFiles@2.1.39, engineFiles@1.1.14)
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/engineFilesV2_1_38.js
  packages/akashic-cli-serve/www/public/external/engineFilesV2_1_39.js
  packages/akashic-cli-serve/www/public/external/engineFilesV3_0_0_beta_2.js
  packages/akashic-cli-serve/www/public/external/engineFilesV3_0_0_beta_3.js
Labels: enhancement

#290 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#291 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.0-beta.3, engineFiles@2.1.39, engineFiles@1.1.14)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#287 アツマールAPIの更新に追従する対応
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
Labels: enhancement

#293 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/javascript-base/package.json
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#292 Delete unnecessary lines from js template file
  packages/akashic-cli-init/build/generateTemplateSource.js
  packages/akashic-cli-init/templates-src-v3/typescript-base/tsconfig.json
  packages/akashic-cli-init/templates-src/typescript-base/tsconfig.json
Labels: enhancement

#296 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.0-beta.3, engineFiles@2.1.39, engineFiles@1.1.14)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#294 Add externalValue to the argument of RunnerManager#createRunner()
  packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
Labels: enhancement
