Repository akashic-games/akashic-cli, pull requests merged in 2020-01, with the labels that each got.

#222 【akashic-cli-export-html】内部コンポーネントの更新(engineFiles@2.1.35, engineFiles@1.1.13)
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/akashic-gameview-web.strip.js
Labels: enhancement

#220 akashic-cli-initのテンプレートディレクトリが依存するakashicモジュールを最新に更新するスクリプトの作成
  packages/akashic-cli-init/build/updateModulesOfTemplates.js
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/package.json
Labels: other

#225 fix: sandbox.config.js in autoSendEvents is deprecated
  packages/akashic-cli-serve/src/client/operator/Operator.ts
  packages/akashic-cli-serve/src/common/types/SandboxConfig.ts
Labels: other

#231 Remove node-v8 from travis.yml and add node-v12
  .travis.yml
Labels: other

#223 fix: loading timing of sandboxConfig
  packages/akashic-cli-serve/src/client/api/ApiClient.ts
  packages/akashic-cli-serve/src/client/operator/Operator.ts
  packages/akashic-cli-serve/src/client/store/ContentEntity.ts
  packages/akashic-cli-serve/src/common/types/ApiResponse.ts
  packages/akashic-cli-serve/src/server/controller/ContentController.ts
  packages/akashic-cli-serve/src/server/controller/RunnerController.ts
  packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
  packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
  packages/akashic-cli-serve/src/server/domain/dynamicRequire.ts
  packages/akashic-cli-serve/src/server/index.ts
  packages/akashic-cli-serve/src/server/route/ApiRoute.ts
  packages/akashic-cli-serve/src/server/route/ContentsRoute.ts
Labels: bug
