Repository akashic-games/akashic-cli, pull requests merged in 2020-06, with the labels that each got.

#322 .npmrcの削除と直下の.npmrcをgit管理外にする対応
  .npmrc
Labels: bug

#323 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#324 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.0-beta.5, engineFiles@2.1.40, engineFiles@1.1.14)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#325 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#328 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#329 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.0-beta.5, engineFiles@2.1.40, engineFiles@1.1.14)
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/akashic-gameview-web.strip.js
Labels: enhancement

#326 publishスクリプトにタグ指定オプションを追加
  package.json
Labels: other

#330 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.0-beta.5, engineFiles@2.1.40, engineFiles@1.1.14)
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/akashic-gameview-web.strip.js
Labels: enhancement

#332 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.0-beta.5, engineFiles@2.1.40, engineFiles@1.1.14)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#333 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.0-beta.5, engineFiles@2.1.40, engineFiles@1.1.14)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#321 akashic-cli-serveでユーザー名表示許諾ダイアログを表示する対応
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/src/client/akashic/AkashicGameViewWeb.d.ts
  packages/akashic-cli-serve/src/client/operator/ExternalPluginOperator.ts
  packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
  packages/akashic-cli-serve/src/client/store/LocalInstanceEntity.ts
  packages/akashic-cli-serve/src/client/view/container/GameScreenContainer.tsx
  packages/akashic-cli-serve/src/client/view/molecule/UsernameDisplayAuthorizationDialog.tsx
  packages/akashic-cli-serve/src/client/view/organism/GameScreen.tsx
  packages/akashic-cli-serve/src/client/view/stories/GameScreen.stories.tsx
Labels: enhancement

#336 【akashic-cli-export-html】内部コンポーネントの更新(engineFiles@3.0.0-beta.5, engineFiles@2.1.41, engineFiles@1.1.14)
  packages/akashic-cli-export-html/templates/engineFilesVersion.json
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_40.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_41.js
Labels: enhancement

#337 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/javascript-base/package.json
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#339 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/javascript-base/package.json
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#348 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#350 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#351 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/javascript-base/package.json
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#341 Add omitUnbundledJs parameter of export
  packages/akashic-cli-commons/src/CliConfig/CliConfigExportHtml.ts
  packages/akashic-cli-commons/src/CliConfig/CliConfigExportZip.ts
Labels: enhancement

#352 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement
