Repository akashic-games/akashic-cli, pull requests merged in 2020-08, with the labels that each got.

#423 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#424 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#426 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#427 【akashic-cli-export-html】内部コンポーネントの更新(engineFiles@3.0.0-beta.7, engineFiles@2.1.43, engineFiles@1.1.15)
  packages/akashic-cli-export-html/templates/engineFilesVersion.json
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_42.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_43.js
Labels: enhancement

#429 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/javascript-base/package.json
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#431 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#433 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/javascript-base/package.json
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#439 【akashic-cli-export-html】内部コンポーネントの更新(engineFiles@3.0.0-beta.7, engineFiles@2.1.46, engineFiles@1.1.16)
  packages/akashic-cli-export-html/templates/engineFilesVersion.json
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_45.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/engineFilesV2_1_46.js
Labels: enhancement

#434 Add ServiceType
  packages/akashic-cli-commons/src/CliConfig/CliConfigExportZip.ts
  packages/akashic-cli-commons/src/CliConfig/CliConfigServe.ts
  packages/akashic-cli-commons/src/GameConfiguration.ts
  packages/akashic-cli-commons/src/ServiceType.ts
  packages/akashic-cli-commons/src/index.ts
Labels: other

#441 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/javascript-base/package.json
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#435 export-zip refactor ServiceType
  packages/akashic-cli-export-html/src/app/exportAtsumaru.ts
  packages/akashic-cli-export-zip/package-lock.json
  packages/akashic-cli-export-zip/spec/src/convertSpec.ts
  packages/akashic-cli-export-zip/src/ServiceType.ts
  packages/akashic-cli-export-zip/src/cli.ts
  packages/akashic-cli-export-zip/src/convert.ts
  packages/akashic-cli-export-zip/src/exportZip.ts
Labels: other

#442 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#443 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#437 serve refactor ServiceType
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/src/client/operator/Operator.ts
  packages/akashic-cli-serve/src/client/store/Store.ts
  packages/akashic-cli-serve/src/client/view/container/DevtoolContainer.tsx
  packages/akashic-cli-serve/src/client/view/container/ToolbarContainer.tsx
  packages/akashic-cli-serve/src/client/view/organism/ToolBar.tsx
  packages/akashic-cli-serve/src/client/view/stories/ToolBar.stories.tsx
  packages/akashic-cli-serve/src/common/types/AppOptions.ts
  packages/akashic-cli-serve/src/common/types/ServiceType.ts
  packages/akashic-cli-serve/src/server/common/ServerGlobalConfig.ts
  packages/akashic-cli-serve/src/server/index.ts
  renovate.json
Labels: other

#444 fix akashic-export-html to run normally
  packages/akashic-cli-export-html/build-template-support/updatefiles.js
  packages/akashic-cli-export-html/templates/template-export-html-v1/js/game-storage.strip.js
  packages/akashic-cli-export-html/templates/template-export-html-v2/js/game-storage.strip.js
  packages/akashic-cli-export-html/templates/template-export-html-v3/js/game-storage.strip.js
Labels: bug

#445 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#448 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#450 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#452 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#454 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#440 [akashic-cli-serve] Follow headless-driver@1.2.0
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/spec/server/SocketIOAMFlowManagerSpec.js
  packages/akashic-cli-serve/src/client/akashic/SocketIOAMFlowClient.ts
  packages/akashic-cli-serve/src/server/domain/SocketIOAMFlowManager.ts
Labels: dependencies, enhancement

#455 adapt to uglify-js major version update
  packages/akashic-cli-export-zip/package-lock.json
  packages/akashic-cli-export-zip/src/convert.ts
  packages/akashic-cli-serve/build/AkashicGameViewWebBuilder.js
  packages/akashic-cli-serve/www/public/external/akashic-gameview-web.strip.js
Labels: bug

#456 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#457 Changed to use package-lock.json in install and uninstall
  packages/akashic-cli-install/spec/installSpec.js
  packages/akashic-cli-install/src/install.ts
  packages/akashic-cli-uninstall/spec/src/uninstallSpec.ts
  packages/akashic-cli-uninstall/src/uninstall.ts
Labels: other

#466 fix to be able to build and test
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: bug

#468 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#473 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#474 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement

#475 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src-v3/typescript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
Labels: enhancement
