Repository akashic-games/akashic-cli, pull requests merged in 2021-08, with the labels that each got.

#816 fix(export): deprecate and always enable --no-omit-empty-js
  packages/akashic-cli-export/spec/src/zip/GameConfigurationUtilSpec.ts
  packages/akashic-cli-export/spec/src/zip/convertSpec.ts
  packages/akashic-cli-export/src/html/exportAtsumaru.ts
  packages/akashic-cli-export/src/zip/GameConfigurationUtil.ts
  packages/akashic-cli-export/src/zip/cli.ts
  packages/akashic-cli-export/src/zip/convert.ts
  packages/akashic-cli-export/src/zip/exportZip.ts
Labels: bug

#815 fix(export): fix wrong bin name 'akashic-cli-zip' to 'akashic-cli-export-zip'
  packages/akashic-cli-export/package.json
Labels: breaking, bug

#817 chore(export): restore removed bin name for compatiblity
  packages/akashic-cli-export/package.json
Labels: other

#819 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#823 Fix akashic-init template spec
  packages/akashic-cli-init/templates-src/game-default/spec/testSpec.ts
  packages/akashic-cli-init/templates-src/game-minimal/spec/testSpec.ts
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: bug

#821 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.19, engineFiles@2.1.56, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#825 【akashic-cli-export】内部コンポーネントの更新(engineFiles@3.0.20, engineFiles@2.1.56, engineFiles@1.1.16)
  packages/akashic-cli-export/src/template/engineFilesVersion.json
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_0_19.js
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_0_20.js
Labels: enhancement

#826 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#827 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.20, engineFiles@2.1.56, engineFiles@1.1.16)
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/engineFilesV3_0_19.js
  packages/akashic-cli-serve/www/public/external/engineFilesV3_0_20.js
Labels: enhancement

#829 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#824 Extend serve --target-service option
  packages/akashic-cli-commons/src/ServiceType.ts
  packages/akashic-cli-serve/src/client/common/createSessionParameter.ts
  packages/akashic-cli-serve/src/client/operator/Operator.ts
  packages/akashic-cli-serve/src/client/view/container/DevtoolContainer.tsx
  packages/akashic-cli-serve/src/client/view/container/ToolbarContainer.tsx
  packages/akashic-cli-serve/src/client/view/molecule/AtsumaruDevtool.tsx
  packages/akashic-cli-serve/src/client/view/molecule/NiconicoDevtool.tsx
  packages/akashic-cli-serve/src/server/index.ts
Labels: enhancement

#830 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement
