Repository akashic-games/akashic-cli, pull requests merged in 2021-05, with the labels that each got.

#756 Modify .gitignore of akashic-init template
  packages/akashic-cli-init/templates-src/typescript-base/.gitignore
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: other

#757 headless-driver@1.7.0 を利用するように
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
Labels: dependencies

#762 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement
