Repository akashic-games/akashic-cli, pull requests merged in 2021-11, with the labels that each got.

#894 fix(export): fix package.json to able to build
  packages/akashic-cli-export/package.json
  packages/akashic-cli-export/src/template/template-export-html-v1/package-lock.json
  packages/akashic-cli-export/src/template/template-export-html-v2/package-lock.json
  packages/akashic-cli-export/src/template/template-export-html-v3/package-lock.json
Labels: bug

#896 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#897 test(commons): use TS in tests
  packages/akashic-cli-commons/package-lock.json
  packages/akashic-cli-commons/package.json
  packages/akashic-cli-commons/spec/NodeModulesSpec.ts
  packages/akashic-cli-commons/spec/src/CliConfig/CliConfigurationFileSpec.ts
  packages/akashic-cli-commons/spec/src/CliConfig/CliConfigurationFileSpec_invalid.ts
  packages/akashic-cli-commons/spec/src/ConfigurationFileSpec.ts
  packages/akashic-cli-commons/spec/src/ConfigurationSpec.ts
  packages/akashic-cli-commons/spec/src/ConsoleLoggerSpec.ts
  packages/akashic-cli-commons/spec/src/LibConfigurationFileSpec.ts
  packages/akashic-cli-commons/spec/src/PromisedNpmSpec.ts
  packages/akashic-cli-commons/spec/src/RenamerSpec.ts
  packages/akashic-cli-commons/spec/src/StringStreamSpec.ts
  packages/akashic-cli-commons/spec/src/UtilSpec.ts
  packages/akashic-cli-commons/spec/support/jasmine.json
  packages/akashic-cli-commons/spec/tsconfig.json
Labels: other

#898 fix(test): fix broken coverages
  packages/akashic-cli-commons/jest.config.js
  packages/akashic-cli-export/jest.config.js
  packages/akashic-cli-lib-manage/jest.config.js
  packages/akashic-cli-serve/jest.config.js
Labels: other

#900 refactor: move FileModule to commons, remove unused functions
  package-lock.json
  packages/akashic-cli-commons/spec/src/FileSystemSpec.ts
  packages/akashic-cli-commons/spec/src/LibConfigurationFileSpec.ts
  packages/akashic-cli-commons/spec/src/NodeModulesSpec.ts
  packages/akashic-cli-commons/src/FileSystem.ts
  packages/akashic-cli-commons/src/LibConfigurationFile.ts
  packages/akashic-cli-commons/src/index.ts
  packages/akashic-cli-scan/src/FileModule.ts
  packages/akashic-cli-scan/src/scanAsset.ts
  packages/akashic-cli-scan/src/scanNodeModules.ts
Labels: other

#904 feat(serve): add Playback devtool
  packages/akashic-cli-serve/src/client/common/DateUtil.ts
  packages/akashic-cli-serve/src/client/operator/DevtoolOperator.ts
  packages/akashic-cli-serve/src/client/operator/LocalInstanceOperator.ts
  packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
  packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
  packages/akashic-cli-serve/src/client/store/LocalInstanceEntity.ts
  packages/akashic-cli-serve/src/client/store/ToolBarUiStore.ts
  packages/akashic-cli-serve/src/client/store/storage.ts
  packages/akashic-cli-serve/src/client/view/App.tsx
  packages/akashic-cli-serve/src/client/view/atom/DevtoolSelectorBar.css
  packages/akashic-cli-serve/src/client/view/atom/ToolIconButton.css
  packages/akashic-cli-serve/src/client/view/atom/ToolSnapshotButton.css
  packages/akashic-cli-serve/src/client/view/atom/ToolSnapshotButton.tsx
  packages/akashic-cli-serve/src/client/view/container/DevtoolContainer.tsx
  packages/akashic-cli-serve/src/client/view/global.css
  packages/akashic-cli-serve/src/client/view/molecule/InstanceControl.tsx
  packages/akashic-cli-serve/src/client/view/molecule/PlaybackDevtool.css
  packages/akashic-cli-serve/src/client/view/molecule/PlaybackDevtool.tsx
  packages/akashic-cli-serve/src/client/view/molecule/PlaybackOptionBar.css
  packages/akashic-cli-serve/src/client/view/molecule/PlaybackOptionBar.tsx
  packages/akashic-cli-serve/src/client/view/molecule/SnapshotDevtool.tsx
  packages/akashic-cli-serve/src/client/view/organism/Devtool.tsx
  packages/akashic-cli-serve/src/client/view/stories/Devtool.stories.tsx
Labels: enhancement

#899 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.2, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/engineFilesV3_1_1.js
  packages/akashic-cli-serve/www/public/external/engineFilesV3_1_2.js
Labels: enhancement

#907 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#893 【akashic-cli-export】内部コンポーネントの更新(engineFiles@3.1.2, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-export/src/template/engineFilesVersion.json
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_1_1.js
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_1_3.js
Labels: enhancement

#908 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#909 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.3, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/engineFilesV3_1_2.js
  packages/akashic-cli-serve/www/public/external/engineFilesV3_1_3.js
Labels: enhancement

#910 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#905 feat(init): overhaul init, remove factory templates and use the default template repository on Github
  packages/akashic-cli-commons/spec/src/FileSystemSpec.ts
  packages/akashic-cli-commons/src/FileSystem.ts
  packages/akashic-cli-init/jest.config.js
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/package.json
  packages/akashic-cli-init/spec/BasicParametersSpec.js
  packages/akashic-cli-init/spec/InitParameterObjectSpec.js
  packages/akashic-cli-init/spec/TemplateMetadataSpec.js
  packages/akashic-cli-init/spec/cloneTemplateSpec.js
  packages/akashic-cli-init/spec/downloadTemplateSpec.js
  packages/akashic-cli-init/spec/initSpec.js
  packages/akashic-cli-init/spec/listTemplatesSpec.js
  packages/akashic-cli-init/spec/support/fixture/local/javascript-minimal/.eslintrc.json
  packages/akashic-cli-init/spec/support/fixture/local/javascript-minimal/.gitignore
  packages/akashic-cli-init/spec/support/fixture/local/javascript-minimal/game.json
  packages/akashic-cli-init/spec/support/fixture/local/javascript-minimal/package.json
  packages/akashic-cli-init/spec/support/fixture/local/javascript-minimal/script/main.js
  packages/akashic-cli-init/spec/support/fixture/remote/javascript.zip
  packages/akashic-cli-init/spec/support/fixture/remote/template-list.json
  packages/akashic-cli-init/spec/support/fixture/remote/typescript.zip
  packages/akashic-cli-init/src/InitParameterObject.ts
  packages/akashic-cli-init/src/TemplateConfig.ts
  packages/akashic-cli-init/src/cli.ts
  packages/akashic-cli-init/src/common/InitCommonOptions.ts
  packages/akashic-cli-init/src/common/TemplateMetadata.ts
  packages/akashic-cli-init/src/copyTemplate.ts
  packages/akashic-cli-init/src/downloadTemplate.ts
  packages/akashic-cli-init/src/extractZipIfNeeded.ts
  packages/akashic-cli-init/src/index.ts
  packages/akashic-cli-init/src/init.ts
  packages/akashic-cli-init/src/init/BasicParameters.ts
  packages/akashic-cli-init/src/init/InitParameterObject.ts
  packages/akashic-cli-init/src/init/TemplateConfig.ts
  packages/akashic-cli-init/src/init/cloneTemplate.ts
  packages/akashic-cli-init/src/init/init.ts
  packages/akashic-cli-init/src/list/ListTemplatesParameterObject.ts
  packages/akashic-cli-init/src/list/listTemplates.ts
  packages/akashic-cli-init/src/listTemplates.ts
  packages/akashic-cli-init/src/readTemplateFile.ts
  packages/akashic-cli-init/src/showTemplateMessage.ts
  packages/akashic-cli-init/tsconfig.json
Labels: enhancement

#912 fix(export): remove obsolete warning messages
  packages/akashic-cli-export/spec/fixtures/sample_game_v3/game.json
  packages/akashic-cli-export/spec/fixtures/sample_game_with_akashic_runtime/game.json
  packages/akashic-cli-export/spec/src/html/exportAtsumaruSpec.ts
  packages/akashic-cli-export/src/html/exportAtsumaru.ts
Labels: bug

#911 feat(init): introduce formatVersion to template.json and template-list.json
  packages/akashic-cli-init/spec/TemplateMetadataSpec.js
  packages/akashic-cli-init/spec/initSpec.js
  packages/akashic-cli-init/spec/support/fixture/remote/template-list.unsupported.json
  packages/akashic-cli-init/src/common/TemplateMetadata.ts
  packages/akashic-cli-init/src/init/TemplateConfig.ts
  packages/akashic-cli-init/template-spec.md
Labels: enhancement

#913 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#917 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.3, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#919 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.3, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#920 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#921 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#922 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.3, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#925 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.3, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#928 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement
