Repository akashic-games/akashic-cli, pull requests merged in 2021-12, with the labels that each got.

#932 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.3, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#933 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#934 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#935 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#936 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.3, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#937 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.3, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#938 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.3, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#926 Change akashic init test to ts
  packages/akashic-cli-init/jest.config.js
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/package.json
  packages/akashic-cli-init/spec/BasicParametersSpec.js
  packages/akashic-cli-init/spec/InitParameterObjectSpec.js
  packages/akashic-cli-init/spec/TemplateMetadataSpec.js
  packages/akashic-cli-init/spec/initSpec.js
  packages/akashic-cli-init/spec/support/mockConfigFile.js
  packages/akashic-cli-init/spec/support/mockPrompt.js
  packages/akashic-cli-init/src/__tests__/.eslintrc.js
  packages/akashic-cli-init/src/__tests__/BasicParametersSpec.ts
  packages/akashic-cli-init/src/__tests__/InitParameterObjectSpec.ts
  packages/akashic-cli-init/src/__tests__/TemplateMetadataSpec.ts
  packages/akashic-cli-init/src/__tests__/cloneTemplateSpec.ts
  packages/akashic-cli-init/src/__tests__/initSpec.ts
  packages/akashic-cli-init/src/__tests__/listTemplatesSpec.ts
  packages/akashic-cli-init/src/__tests__/support/fixture/local/javascript-minimal/.eslintrc.json
  packages/akashic-cli-init/src/__tests__/support/fixture/local/javascript-minimal/.gitignore
  packages/akashic-cli-init/src/__tests__/support/fixture/local/javascript-minimal/game.json
  packages/akashic-cli-init/src/__tests__/support/fixture/local/javascript-minimal/package.json
  packages/akashic-cli-init/src/__tests__/support/fixture/local/javascript-minimal/script/main.js
  packages/akashic-cli-init/src/__tests__/support/fixture/remote/javascript.zip
  packages/akashic-cli-init/src/__tests__/support/fixture/remote/template-list.json
  packages/akashic-cli-init/src/__tests__/support/fixture/remote/template-list.unsupported.json
  packages/akashic-cli-init/src/__tests__/support/fixture/remote/typescript.zip
  packages/akashic-cli-init/src/__tests__/support/mockConfigFile.ts
  packages/akashic-cli-init/src/__tests__/support/mockPrompt.ts
  packages/akashic-cli-init/src/__tests__/tsconfig.json
Labels: other

#942 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#944 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#939 Mock value of akashic-runtime-version-table in export html test
  packages/akashic-cli-export/package-lock.json
  packages/akashic-cli-export/package.json
  packages/akashic-cli-export/spec/src/html/apiUtilSpec.ts
  packages/akashic-cli-export/spec/src/html/exportAtsumaruSpec.ts
  packages/akashic-cli-export/spec/src/html/exportHTMLSpec.ts
  packages/akashic-cli-export/spec/tsconfig.json
  packages/akashic-cli-export/tsconfig.json
Labels: other

#945 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.4, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#947 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#955 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.4, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/akashic-gameview-web.strip.js
Labels: enhancement

#957 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.4, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#959 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.4, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#954 Fix eslint in devdependencies of commons
  packages/akashic-cli-commons/package.json
  packages/akashic-cli-commons/src/LintUtil.ts
  packages/akashic-cli-export/spec/src/html/convertUtilSpec.ts
  packages/akashic-cli-export/src/html/convertBundle.ts
  packages/akashic-cli-export/src/html/convertNoBundle.ts
  packages/akashic-cli-export/src/html/convertUtil.ts
  packages/akashic-cli-export/src/zip/convert.ts
Labels: bug

#961 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.4, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#953 Save allowed url to akashicrc
  packages/akashic-cli-init/README.md
  packages/akashic-cli-init/src/__tests__/InitParameterObjectSpec.ts
  packages/akashic-cli-init/src/__tests__/cloneTemplateSpec.ts
  packages/akashic-cli-init/src/__tests__/listTemplatesSpec.ts
  packages/akashic-cli-init/src/common/InitCommonOptions.ts
  packages/akashic-cli-init/src/init/InitParameterObject.ts
Labels: enhancement

#916 Mod akashic-init --registry option to --repository
  packages/akashic-cli-commons/src/CliConfig/CliConfigInit.ts
  packages/akashic-cli-init/README.md
  packages/akashic-cli-init/src/__tests__/InitParameterObjectSpec.ts
  packages/akashic-cli-init/src/__tests__/cloneTemplateSpec.ts
  packages/akashic-cli-init/src/__tests__/listTemplatesSpec.ts
  packages/akashic-cli-init/src/cli.ts
  packages/akashic-cli-init/src/common/InitCommonOptions.ts
  packages/akashic-cli-init/src/init/InitParameterObject.ts
  packages/akashic-cli-init/src/init/cloneTemplate.ts
  packages/akashic-cli-init/src/init/init.ts
Labels: enhancement

#967 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.4, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#968 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.4, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement
