Repository akashic-games/akashic-cli, pull requests merged in 2021-10, with the labels that each got.

#862 【akashic-cli-export】内部コンポーネントの更新(engineFiles@3.1.0, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-export/src/template/engineFilesVersion.json
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_0_22.js
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_1_0.js
Labels: enhancement

#864 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.0, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/engineFilesV3_0_22.js
  packages/akashic-cli-serve/www/public/external/engineFilesV3_1_0.js
Labels: enhancement

#865 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#853 Support https serve
  packages/akashic-cli-commons/src/CliConfig/CliConfigServe.ts
  packages/akashic-cli-serve/src/client/api/socketInstance.ts
  packages/akashic-cli-serve/src/server/common/ServerContentLocator.ts
  packages/akashic-cli-serve/src/server/common/ServerGlobalConfig.ts
  packages/akashic-cli-serve/src/server/controller/ContentController.ts
  packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
  packages/akashic-cli-serve/src/server/index.ts
Labels: enhancement

#867 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#868 fix(serve): fix --debug-playlog and accept absolute path
  packages/akashic-cli-serve/src/server/index.ts
Labels: bug

#869 feat(init): support to initialize project from GitHub repo
  packages/akashic-cli-init/spec/.gitignore
  packages/akashic-cli-init/spec/cloneTemplateSpec.js
  packages/akashic-cli-init/src/InitParameterObject.ts
  packages/akashic-cli-init/src/cli.ts
  packages/akashic-cli-init/src/cloneTemplate.ts
  packages/akashic-cli-init/src/init.ts
Labels: enhancement

#872 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#874 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#881 feat(init): GitHub Enterprise でのテンプレート初期化に対応
  packages/akashic-cli-export/src/template/template-export-html-v1/package-lock.json
  packages/akashic-cli-export/src/template/template-export-html-v2/package-lock.json
  packages/akashic-cli-export/src/template/template-export-html-v3/package-lock.json
  packages/akashic-cli-extra/spec/src/config/configSpec.ts
  packages/akashic-cli-extra/src/config/config.ts
  packages/akashic-cli-init/README.md
  packages/akashic-cli-init/jest.config.js
  packages/akashic-cli-init/spec/.gitignore
  packages/akashic-cli-init/spec/InitParameterObjectSpec.js
  packages/akashic-cli-init/spec/cloneTemplateSpec.js
  packages/akashic-cli-init/src/InitParameterObject.ts
  packages/akashic-cli-init/src/cli.ts
  packages/akashic-cli-init/src/cloneTemplate.ts
  packages/akashic-cli-init/src/init.ts
Labels: bug, enhancement

#883 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement
