Repository akashic-games/akashic-cli, pull requests merged in 2021-07, with the labels that each got.

#783 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#773 akashic-cli-scan のリファクタリング
  packages/akashic-cli-scan/package-lock.json
  packages/akashic-cli-scan/package.json
  packages/akashic-cli-scan/spec/src/AssetModuleSpec.ts
  packages/akashic-cli-scan/spec/src/ConfigurationSpec.ts
  packages/akashic-cli-scan/spec/src/FileModuleSpec.ts
  packages/akashic-cli-scan/spec/src/LibConfigurationSpec.ts
  packages/akashic-cli-scan/spec/src/helpers/.gitkeep
  packages/akashic-cli-scan/spec/src/scanAssetSpec.ts
  packages/akashic-cli-scan/spec/src/scanNodeModulesSpec.ts
  packages/akashic-cli-scan/spec/src/scanSpec.ts
  packages/akashic-cli-scan/spec/src/scanUtilsSpec.ts
  packages/akashic-cli-scan/spec/tsconfig.json
  packages/akashic-cli-scan/src/AssetModule.ts
  packages/akashic-cli-scan/src/Configuration.ts
  packages/akashic-cli-scan/src/FileModule.ts
  packages/akashic-cli-scan/src/LibConfiguration.ts
  packages/akashic-cli-scan/src/cli.ts
  packages/akashic-cli-scan/src/getAudioDuration.ts
  packages/akashic-cli-scan/src/index.ts
  packages/akashic-cli-scan/src/scan.ts
  packages/akashic-cli-scan/src/scanAsset.ts
  packages/akashic-cli-scan/src/scanNodeModules.ts
  packages/akashic-cli-scan/src/scanUtils.ts
  packages/akashic-cli-scan/src/types.ts
  packages/akashic-cli-scan/src/watchAsset.ts
Labels: other

#785 Fix init generate template
  packages/akashic-cli-init/build/generateTemplateSource.js
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: bug

#787 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.17, engineFiles@2.1.54, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#788 feat(serve): add service property to the session parameter
  packages/akashic-cli-serve/src/client/common/createSessionParameter.ts
  packages/akashic-cli-serve/src/client/common/defaultSessionParameter.ts
  packages/akashic-cli-serve/src/client/operator/Operator.ts
Labels: enhancement

#798 【akashic-cli-export】内部コンポーネントの更新(engineFiles@3.0.18, engineFiles@2.1.54, engineFiles@1.1.16)
  packages/akashic-cli-export/src/template/engineFilesVersion.json
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_0_17.js
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_0_18.js
Labels: enhancement

#799 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#800 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.18, engineFiles@2.1.54, engineFiles@1.1.16)
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/engineFilesV3_0_17.js
  packages/akashic-cli-serve/www/public/external/engineFilesV3_0_18.js
Labels: enhancement

#804 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#806 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#810 msgpack パーサーの追加
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/src/client/akashic/SocketIOAMFlowClient.ts
  packages/akashic-cli-serve/src/client/api/socketInstance.ts
  packages/akashic-cli-serve/src/common/MsgpackParser.ts
  packages/akashic-cli-serve/src/server/index.ts
Labels: other

#811 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#790 Add eslint config to akashic cli
  packages/akashic-cli/.eslintrc.js
  packages/akashic-cli/package-lock.json
  packages/akashic-cli/package.json
  packages/akashic-cli/src/ui.ts
Labels: other

#792 Add akashic-eslint-config to export
  packages/akashic-cli-export/.eslintrc.js
  packages/akashic-cli-export/package-lock.json
  packages/akashic-cli-export/package.json
  packages/akashic-cli-export/spec/.eslintrc.js
  packages/akashic-cli-export/spec/src/html/apiUtilSpec.ts
  packages/akashic-cli-export/spec/src/html/exportAtsumaruSpec.ts
  packages/akashic-cli-export/spec/src/html/exportHTMLSpec.ts
  packages/akashic-cli-export/spec/src/pdi/gameExternalStorageSpec.ts
  packages/akashic-cli-export/spec/src/zip/GameConfigurationUtilSpec.ts
  packages/akashic-cli-export/spec/src/zip/convertSpec.ts
  packages/akashic-cli-export/src/html/cli.ts
  packages/akashic-cli-export/src/html/convertBundle.ts
  packages/akashic-cli-export/src/html/convertNoBundle.ts
  packages/akashic-cli-export/src/html/convertUtil.ts
  packages/akashic-cli-export/src/html/exportAtsumaru.ts
  packages/akashic-cli-export/src/html/exportHTML.ts
  packages/akashic-cli-export/src/pdi/LocalScriptAsset.ts
  packages/akashic-cli-export/src/pdi/LocalScriptAssetV3.ts
  packages/akashic-cli-export/src/pdi/LocalTextAsset.ts
  packages/akashic-cli-export/src/pdi/LocalTextAssetV3.ts
  packages/akashic-cli-export/src/pdi/storage/GameExternalStorage.ts
  packages/akashic-cli-export/src/pdi/storage/content-storage-types/GameExternalStorageLike.ts
  packages/akashic-cli-export/src/pdi/storage/content-storage-types/types.ts
  packages/akashic-cli-export/src/zip/cli.ts
  packages/akashic-cli-export/src/zip/convert.ts
  packages/akashic-cli-export/src/zip/exportZip.ts
Labels: other

#793 Add akashic/eslint-config to extra
  packages/akashic-cli-extra/.eslintrc.js
  packages/akashic-cli-extra/package-lock.json
  packages/akashic-cli-extra/package.json
  packages/akashic-cli-extra/spec/.eslintrc.js
  packages/akashic-cli-extra/spec/src/config/configSpec.ts
  packages/akashic-cli-extra/spec/src/modify/modifySpec.ts
  packages/akashic-cli-extra/spec/src/stat/statSpec.ts
  packages/akashic-cli-extra/src/config/cli.ts
  packages/akashic-cli-extra/src/config/config.ts
  packages/akashic-cli-extra/src/modify/cli.ts
  packages/akashic-cli-extra/src/modify/modify.ts
  packages/akashic-cli-extra/src/stat/cli.ts
  packages/akashic-cli-extra/src/stat/stat.ts
Labels: other

#795 Add eslint config to lib manage
  packages/akashic-cli-lib-manage/.eslintrc.js
  packages/akashic-cli-lib-manage/package-lock.json
  packages/akashic-cli-lib-manage/package.json
  packages/akashic-cli-lib-manage/src/install/Configuration.ts
  packages/akashic-cli-lib-manage/src/install/cli.ts
  packages/akashic-cli-lib-manage/src/install/index.ts
  packages/akashic-cli-lib-manage/src/install/install.ts
  packages/akashic-cli-lib-manage/src/uninstall/Configuration.ts
  packages/akashic-cli-lib-manage/src/uninstall/cli.ts
  packages/akashic-cli-lib-manage/src/uninstall/index.ts
  packages/akashic-cli-lib-manage/src/uninstall/uninstall.ts
  packages/akashic-cli-lib-manage/src/update/cli.ts
Labels: other

#797 Add eslint to serve
  packages/akashic-cli-export/package-lock.json
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/src/client/.eslintrc.js
  packages/akashic-cli-serve/src/client/akashic/AkashicGameViewWeb.d.ts
  packages/akashic-cli-serve/src/client/akashic/GameViewManager.ts
  packages/akashic-cli-serve/src/client/akashic/SocketIOAMFlowClient.ts
  packages/akashic-cli-serve/src/client/akashic/TestbedScriptAsset.ts
  packages/akashic-cli-serve/src/client/api/ApiClient.ts
  packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
  packages/akashic-cli-serve/src/client/atsumaru/ScoreboardData.ts
  packages/akashic-cli-serve/src/client/atsumaru/ScreenshotModalResults.ts
  packages/akashic-cli-serve/src/client/atsumaru/TweetSettings.ts
  packages/akashic-cli-serve/src/client/common/ClientContentLocator.ts
  packages/akashic-cli-serve/src/client/common/DateUtil.ts
  packages/akashic-cli-serve/src/client/common/createSessionParameter.ts
  packages/akashic-cli-serve/src/client/operator/DevtoolOperator.ts
  packages/akashic-cli-serve/src/client/operator/LocalInstanceOperator.ts
  packages/akashic-cli-serve/src/client/operator/Operator.ts
  packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
  packages/akashic-cli-serve/src/client/operator/UiOperator.ts
  packages/akashic-cli-serve/src/client/store/CoeLimitedPluginEntity.ts
  packages/akashic-cli-serve/src/client/store/CoePluginEntity.ts
  packages/akashic-cli-serve/src/client/store/ContentEntity.ts
  packages/akashic-cli-serve/src/client/store/ContentStore.ts
  packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
  packages/akashic-cli-serve/src/client/store/LocalInstanceEntity.ts
  packages/akashic-cli-serve/src/client/store/NicoPluginEntity.ts
  packages/akashic-cli-serve/src/client/store/PlayEntity.ts
  packages/akashic-cli-serve/src/client/store/PlayStore.ts
  packages/akashic-cli-serve/src/client/store/ProfilerStore.ts
  packages/akashic-cli-serve/src/client/store/ServerInstanceEntity.ts
  packages/akashic-cli-serve/src/client/store/Store.ts
  packages/akashic-cli-serve/src/client/store/storage.ts
  packages/akashic-cli-serve/src/common/MsgpackParser.ts
  packages/akashic-cli-serve/src/common/types/ApiResponse.ts
  packages/akashic-cli-serve/src/common/types/ContentDesc.ts
  packages/akashic-cli-serve/src/common/types/TestbedEvent.ts
  packages/akashic-cli-serve/src/server/.eslintrc.js
  packages/akashic-cli-serve/src/server/common/types/DumpedPlaylog.ts
  packages/akashic-cli-serve/src/server/controller/ContentController.ts
  packages/akashic-cli-serve/src/server/controller/HealthCheckController.ts
  packages/akashic-cli-serve/src/server/controller/PlayController.ts
  packages/akashic-cli-serve/src/server/controller/PlayTokenController.ts
  packages/akashic-cli-serve/src/server/controller/PlayerIdController.ts
  packages/akashic-cli-serve/src/server/controller/RunnerController.ts
  packages/akashic-cli-serve/src/server/controller/SandboxConfigController.ts
  packages/akashic-cli-serve/src/server/controller/StartupOptionsController.ts
  packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
  packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
  packages/akashic-cli-serve/src/server/domain/PlayStore.ts
  packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
  packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
  packages/akashic-cli-serve/src/server/domain/SocketIOAMFlowManager.ts
  packages/akashic-cli-serve/src/server/domain/dynamicRequire.ts
  packages/akashic-cli-serve/src/server/index.ts
  packages/akashic-cli-serve/src/server/route/ApiRoute.ts
  packages/akashic-cli-serve/src/server/route/ContentsRoute.ts
  packages/akashic-cli-serve/src/server/route/HealthCheckRoute.ts
Labels: other

#796 Add eslint config to scan
  packages/akashic-cli-scan/.eslintrc.js
  packages/akashic-cli-scan/package-lock.json
  packages/akashic-cli-scan/package.json
  packages/akashic-cli-scan/src/AssetModule.ts
  packages/akashic-cli-scan/src/cli.ts
  packages/akashic-cli-scan/src/getAudioDuration.ts
  packages/akashic-cli-scan/src/scanNodeModules.ts
  packages/akashic-cli-scan/src/scanUtils.ts
  packages/akashic-cli-scan/src/types.ts
  packages/akashic-cli-scan/src/watchAsset.ts
Labels: other

#794 Add eslint config to init
  packages/akashic-cli-init/.eslintrc.js
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/package.json
  packages/akashic-cli-init/src/BasicParameters.ts
  packages/akashic-cli-init/src/InitParameterObject.ts
  packages/akashic-cli-init/src/cli.ts
  packages/akashic-cli-init/src/copyTemplate.ts
  packages/akashic-cli-init/src/downloadTemplate.ts
  packages/akashic-cli-init/src/extractZipIfNeeded.ts
  packages/akashic-cli-init/src/init.ts
Labels: other

#813 Fix isEmptyScriptJs() in export-zip
  packages/akashic-cli-export/spec/src/zip/GameConfigurationUtilSpec.ts
  packages/akashic-cli-export/src/zip/GameConfigurationUtil.ts
Labels: bug

#814 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#812 fix: fix for Windows, enable Windows tests in CI
  .gitattributes
  .github/workflows/test.yml
  package-lock.json
  packages/akashic-cli-commons/src/NodeModules.ts
  packages/akashic-cli-export/spec/src/zip/convertSpec.ts
  packages/akashic-cli-export/src/zip/convert.ts
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/package.json
  packages/akashic-cli-init/spec/downloadTemplateSpec.js
  test/e2e.js
Labels: bug
