Repository akashic-games/akashic-cli, pull requests merged in 2021-04, with the labels that each got.

#727 【akashic-cli-export-html】内部コンポーネントの更新(engineFiles@3.0.11, engineFiles@2.1.53, engineFiles@1.1.16)
  packages/akashic-cli-export-html/templates/engineFilesVersion.json
  packages/akashic-cli-export-html/templates/template-export-html-v3/js/engineFilesV3_0_10.js
  packages/akashic-cli-export-html/templates/template-export-html-v3/js/engineFilesV3_0_11.js
Labels: enhancement

#728 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#729 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.0.11, engineFiles@2.1.53, engineFiles@1.1.16)
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/engineFilesV3_0_10.js
  packages/akashic-cli-serve/www/public/external/engineFilesV3_0_11.js
Labels: enhancement

#730 fix broken CHANGELOG.md and make updateChangelog.js more robust
  CHANGELOG.md
  build/updateChangelog.js
  package-lock.json
Labels: other

#731 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#732 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#736 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#737 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#722 Add experimentalOpen to CliConfigServe
  packages/akashic-cli-commons/src/CliConfig/CliConfigServe.ts
Labels: enhancement

#740 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#724 Add experimental-open to serve
  packages/akashic-cli-serve/README.md
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/src/client/bootstrap.tsx
  packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
  packages/akashic-cli-serve/src/client/store/ContentEntity.ts
  packages/akashic-cli-serve/src/client/store/storage.ts
  packages/akashic-cli-serve/src/common/types/AppOptions.ts
  packages/akashic-cli-serve/src/common/types/ContentDesc.ts
  packages/akashic-cli-serve/src/server/common/ServerGlobalConfig.ts
  packages/akashic-cli-serve/src/server/controller/ContentController.ts
  packages/akashic-cli-serve/src/server/controller/StartupOptionsController.ts
  packages/akashic-cli-serve/src/server/index.ts
Labels: enhancement

#743 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#734 Fix akashic-cli-init template spec files
  packages/akashic-cli-init/build/generateTemplateSource.js
  packages/akashic-cli-init/templates-src/game-default/spec/testSpec.ts
  packages/akashic-cli-init/templates-src/game-minimal/spec/testSpec.ts
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/spec/testSpec.ts
  packages/akashic-cli-init/templates-src/typescript-base/spec/testSpec.ts
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#744 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#742 v3 系の engine-files を外部から指定できるように
  package-lock.json
  packages/akashic-cli-serve/README.md
  packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
  packages/akashic-cli-serve/src/server/global.d.ts
  packages/akashic-cli-serve/src/server/index.ts
Labels: enhancement

#747 feat(serve): use headless-driver@1.6.0
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
Labels: dependencies, enhancement

#717 save opreration plugin scripts when export
  package-lock.json
  packages/akashic-cli-commons/src/NodeModules.ts
  packages/akashic-cli-export/.eslintrc.js
  packages/akashic-cli-export/.gitignore
  packages/akashic-cli-export/package-lock.json
  packages/akashic-cli-export/package.json
  packages/akashic-cli-export/spec/fixtures/simple_game_with_operation_plugins/game.json
  packages/akashic-cli-export/spec/fixtures/simple_game_with_operation_plugins/node_modules/@hoge/testmodule/lib/ModuleA.js
  packages/akashic-cli-export/spec/fixtures/simple_game_with_operation_plugins/node_modules/@hoge/testmodule/lib/ModuleB.js
  packages/akashic-cli-export/spec/fixtures/simple_game_with_operation_plugins/node_modules/@hoge/testmodule/lib/ModuleC.js
  packages/akashic-cli-export/spec/fixtures/simple_game_with_operation_plugins/node_modules/@hoge/testmodule/lib/index.js
  packages/akashic-cli-export/spec/fixtures/simple_game_with_operation_plugins/package.json
  packages/akashic-cli-export/spec/fixtures/simple_game_with_operation_plugins/script/bar.js
  packages/akashic-cli-export/spec/fixtures/simple_game_with_operation_plugins/script/foo.js
  packages/akashic-cli-export/spec/fixtures/simple_game_with_operation_plugins/script/main.js
  packages/akashic-cli-export/spec/src/zip/GameConfigurationUtilSpec.ts
  packages/akashic-cli-export/spec/src/zip/convertSpec.ts
  packages/akashic-cli-export/src/zip/GameConfigurationUtil.ts
  packages/akashic-cli-export/src/zip/convert.ts
Labels: bug

#750 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement
