Repository akashic-games/akashic-cli, pull requests merged in 2021-02, with the labels that each got.

#656 add test of akashic-li-init template in test/e2e.js
  test/e2e.js
Labels: other

#675 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#676 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#677 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#680 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#681 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#673 add publish script as npm-scripts
  package.json
Labels: other

#683 Rename RPG-Atsumaru -> GAME-atsumaru
  packages/akashic-cli-commons/src/ServiceType.ts
  packages/akashic-cli-export-html/src/app/cli.ts
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/_bootstrap.ts
  packages/akashic-cli-init/templates-src/game-shin-ichiba-ranking/src/main.ts
  packages/akashic-cli-init/templates-src/javascript-base/README.md
  packages/akashic-cli-init/templates-src/typescript-base/README.md
  packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
  packages/akashic-cli-serve/src/client/atsumaru/ScoreboardData.ts
Labels: other

#684 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#686 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#688 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#689 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#692 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/javascript-base/package.json
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#694 akashic-cli-initのテンプレート中の内部モジュール更新
  packages/akashic-cli-init/templates-src/typescript-base/package.json
  packages/akashic-cli-init/templates/javascript-minimal.zip
  packages/akashic-cli-init/templates/javascript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/javascript.zip
  packages/akashic-cli-init/templates/typescript-minimal.zip
  packages/akashic-cli-init/templates/typescript-shin-ichiba-ranking.zip
  packages/akashic-cli-init/templates/typescript.zip
Labels: enhancement

#685 Fix warning message of akashic-cli-stat
  packages/akashic-cli-stat/spec/statSpec.js
  packages/akashic-cli-stat/src/stat.ts
Labels: bug
