Repository akashic-games/akashic-cli, pull requests merged in 2022-01, with the labels that each got.

#971 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.4, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#975 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.4, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#976 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.4, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#960 feat(serve): playlogClientファイルを外部から指定できるようにする対応
  packages/akashic-cli-serve/README.md
  packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
  packages/akashic-cli-serve/src/server/index.ts
Labels: enhancement

#918 feat(serve): akashic-cli-serveに外部から接続するための機能を追加
  package-lock.json
  package.json
  packages/akashic-cli-commons/src/CliConfig/CliConfigServe.ts
  packages/akashic-cli-serve/README.md
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/src/client/api/ApiClient.ts
  packages/akashic-cli-serve/src/client/api/Subscriber.ts
  packages/akashic-cli-serve/src/client/api/apiClientInstance.ts
  packages/akashic-cli-serve/src/client/api/createSocketInstance.ts
  packages/akashic-cli-serve/src/client/api/socketInstance.ts
  packages/akashic-cli-serve/src/client/operator/Operator.ts
  packages/akashic-cli-serve/src/client/store/ContentEntity.ts
  packages/akashic-cli-serve/src/client/store/ContentStore.ts
  packages/akashic-cli-serve/src/client/store/PlayEntity.ts
  packages/akashic-cli-serve/src/client/store/PlayStore.ts
  packages/akashic-cli-serve/src/client/store/ServerInstanceEntity.ts
  packages/akashic-cli-serve/src/client/store/Store.ts
  packages/akashic-cli-serve/src/client/store/storage.ts
  packages/akashic-cli-serve/src/client/tsconfig.json
  packages/akashic-cli-serve/src/client/tsconfig.module.json
  packages/akashic-cli-serve/src/server/domain/EngineConfig.ts
  packages/akashic-cli-serve/src/server/domain/PlayStore.ts
  packages/akashic-cli-serve/src/server/index.ts
  packages/akashic-cli-serve/www/public/external/playlogClientV3_2_1.js
Labels: enhancement

#978 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.4, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#982 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.4, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#977 fix behavior of template.json in init
  packages/akashic-cli-init/src/__tests__/initSpec.ts
  packages/akashic-cli-init/src/init/init.ts
Labels: bug

#985 【akashic-cli-export】内部コンポーネントの更新(engineFiles@3.1.5, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-export/src/template/engineFilesVersion.json
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_1_4.js
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_1_5.js
Labels: enhancement

#986 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.5, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/engineFilesV3_1_4.js
  packages/akashic-cli-serve/www/public/external/engineFilesV3_1_5.js
Labels: enhancement

#979 add serve option to README
  packages/akashic-cli-serve/README.md
Labels: other

#987 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.5, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#988 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.5, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
Labels: enhancement

#983 Add --debug-override-engine-files option to export html
  packages/akashic-cli-commons/src/CliConfig/CliConfigExportHtml.ts
  packages/akashic-cli-export/spec/fixtures/engineFilesV3_1_99.js
  packages/akashic-cli-export/spec/src/html/exportHTMLSpec.ts
  packages/akashic-cli-export/src/html/cli.ts
  packages/akashic-cli-export/src/html/convertBundle.ts
  packages/akashic-cli-export/src/html/convertNoBundle.ts
  packages/akashic-cli-export/src/html/convertUtil.ts
  packages/akashic-cli-export/src/html/exportHTML.ts
Labels: enhancement

#994 【akashic-cli-serve】内部コンポーネントの更新(engineFiles@3.1.5, engineFiles@2.1.57, engineFiles@1.1.16)
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/akashic-gameview-web.strip.js
Labels: enhancement
