Repository akashic-games/akashic-cli, pull requests merged in 2022-08, with the labels that each got.

#1091 Mod renovate rule
  renovate.json
Labels: other

#1089 Use engine files alias for serve
  packages/akashic-cli-serve/build/updateEngineFiles.js
  packages/akashic-cli-serve/package.json
  renovate.json
Labels: other

#1090 fix false positive and add warn.drawOutOfCanvas on sandboxConfig
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/src/client/akashic/GameViewManager.ts
  packages/akashic-cli-serve/src/client/akashic/RuntimeWarning.ts
  packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
  packages/akashic-cli-serve/src/client/store/LocalInstanceEntity.ts
  packages/akashic-cli-serve/src/client/store/NotificationUiStore.ts
  packages/akashic-cli-serve/src/client/store/Store.ts
  packages/akashic-cli-serve/src/common/types/SandboxConfig.ts
Labels: bug, enhancement

#1097 【akashic-cli-export】内部コンポーネントの更新(engineFiles@3.2.4, engineFiles@2.2.1, engineFiles@1.2.1)
  packages/akashic-cli-export/src/template/engineFilesVersion.json
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_2_3.js
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_2_4.js
Labels: enhancement

#1105 Use sandbox configration
  packages/akashic-cli-serve/config/engineFilesVersion.json
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/src/client/store/ContentEntity.ts
  packages/akashic-cli-serve/src/client/view/container/DevtoolContainer.tsx
  packages/akashic-cli-serve/src/client/view/container/GameScreenContainer.tsx
  packages/akashic-cli-serve/src/common/types/ApiResponse.ts
  packages/akashic-cli-serve/src/common/types/ContentDesc.ts
  packages/akashic-cli-serve/src/common/types/SandboxConfig.ts
  packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
  packages/akashic-cli-serve/www/public/external/engineFilesV3_2_3.js
  packages/akashic-cli-serve/www/public/external/engineFilesV3_2_4.js
Labels: other

#1114 Support server.external in akashic-cli-serve
  packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
  packages/akashic-cli-serve/src/server/domain/SandboxConfigs.ts
Labels: enhancement
