Repository akashic-games/akashic-cli, pull requests merged in 2023-11, with the labels that each got.

#1288 Modify to display stat results when export-zip is output
  packages/akashic-cli-export/package-lock.json
  packages/akashic-cli-export/package.json
  packages/akashic-cli-export/src/zip/exportZip.ts
Labels: enhancement

#1290 feat: use @akashic/agvw
  packages/akashic-cli-serve/.gitignore
  packages/akashic-cli-serve/build/AkashicGameViewWebBuilder.js
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/akashic-gameview-web.strip.js
  packages/akashic-cli-serve/www/public/index.html
Labels: other

#1291 Revert "feat: use @akashic/agvw"
  packages/akashic-cli-serve/.gitignore
  packages/akashic-cli-serve/build/AkashicGameViewWebBuilder.js
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/akashic-gameview-web.strip.js
  packages/akashic-cli-serve/www/public/index.html
Labels: bug

#1292 feat: use @akashic/agvw
  packages/akashic-cli-serve/.gitignore
  packages/akashic-cli-serve/build/AkashicGameViewWebBuilder.js
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/www/public/external/akashic-gameview-web.strip.js
  packages/akashic-cli-serve/www/public/index.html
Labels: bug

#1289 Add resolveAkashicRuntime option to export-zip
  packages/akashic-cli-commons/src/CliConfig/CliConfigExportZip.ts
  packages/akashic-cli-export/spec/src/zip/cliSpec.ts
  packages/akashic-cli-export/spec/src/zip/convertSpec.ts
  packages/akashic-cli-export/src/zip/cli.ts
  packages/akashic-cli-export/src/zip/convert.ts
  packages/akashic-cli-export/src/zip/exportZip.ts
Labels: enhancement

#1297 fix(serve): fix -w causes reload twice
  packages/akashic-cli-serve/src/server/domain/GameConfigs.ts
  packages/akashic-cli-serve/src/server/index.ts
Labels: bug
