Repository akashic-games/akashic-cli, pull requests merged in 2023-07, with the labels that each got.

#1251 fix(export): fix crash on --hash-filename and hint.extensions
  packages/akashic-cli-commons/package-lock.json
  packages/akashic-cli-commons/package.json
  packages/akashic-cli-export/package-lock.json
  packages/akashic-cli-export/package.json
  packages/akashic-cli-export/spec/fixtures/game_hint_exts/audio/dummyse.aac
  packages/akashic-cli-export/spec/fixtures/game_hint_exts/audio/dummyse.invalidext
  packages/akashic-cli-export/spec/fixtures/game_hint_exts/audio/dummyse.m4a
  packages/akashic-cli-export/spec/fixtures/game_hint_exts/audio/dummyse.ogg
  packages/akashic-cli-export/spec/fixtures/game_hint_exts/game.json
  packages/akashic-cli-export/spec/fixtures/game_hint_exts/package.json
  packages/akashic-cli-export/spec/fixtures/game_hint_exts/script/main.js
  packages/akashic-cli-export/spec/src/html/utilsSpec.ts
  packages/akashic-cli-export/src/html/Utils.ts
  packages/akashic-cli-lib-manage/package-lock.json
  packages/akashic-cli-lib-manage/package.json
  packages/akashic-cli-scan/package-lock.json
  packages/akashic-cli-scan/package.json
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
Labels: bug

#1253 feat(serve): support ScriptAsset#exports
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/src/client/akashic/GameViewManager.ts
  packages/akashic-cli-serve/src/client/akashic/TestbedScriptAsset.ts
  packages/akashic-cli-serve/src/server/controller/ScriptAssetController.ts
Labels: enhancement

#1257 Add game.json validation for export-zip nicolive option
  packages/akashic-cli-export/spec/src/zip/convertSpec.ts
  packages/akashic-cli-export/src/zip/convert.ts
Labels: other

#1259 Support shouMenu of sandbox.config.js in serve
  packages/akashic-cli-serve/src/client/store/ToolBarUiStore.ts
  packages/akashic-cli-serve/src/client/store/storage.ts
Labels: enhancement
