Repository akashic-games/akashic-cli, pull requests merged in 2023-04, with the labels that each got.

#1213 Fix to add extension to moduleMainScripts in akashic-cli-scan
  packages/akashic-cli-commons/spec/src/NodeModulesSpec.ts
  packages/akashic-cli-commons/src/NodeModules.ts
  packages/akashic-cli-lib-manage/package-lock.json
  packages/akashic-cli-lib-manage/package.json
  packages/akashic-cli-lib-manage/spec/src/install/installSpec.ts
  packages/akashic-cli-lib-manage/spec/src/uninstall/uninstallSpec.ts
  packages/akashic-cli-lib-manage/spec/tsconfig.json
  packages/akashic-cli-lib-manage/tsconfig.json
  packages/akashic-cli-scan/spec/src/scanNodeModulesSpec.ts
Labels: bug

#1221 feat(serve): add --debug-trusted-iframe option
  packages/akashic-cli-commons/src/CliConfig/CliConfigServe.ts
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/src/client/akashic/GameViewManager.ts
  packages/akashic-cli-serve/src/client/operator/Operator.ts
  packages/akashic-cli-serve/src/client/store/LocalInstanceEntity.ts
  packages/akashic-cli-serve/src/client/store/PlayEntity.ts
  packages/akashic-cli-serve/src/common/types/AppOptions.ts
  packages/akashic-cli-serve/src/server/common/ServerGlobalConfig.ts
  packages/akashic-cli-serve/src/server/controller/StartupOptionsController.ts
  packages/akashic-cli-serve/src/server/index.ts
  packages/akashic-cli-serve/www/public/external/akashic-gameview-web.strip.js
Labels: enhancement

#1219 Add parameters for Nicolive to commons
  packages/akashic-cli-commons/src/CliConfig/CliConfigExportZip.ts
  packages/akashic-cli-commons/src/GameConfiguration.ts
Labels: enhancement

#1220 Add --nicolive option to akashic-cli-export-zip
  packages/akashic-cli-commons/src/GameConfiguration.ts
  packages/akashic-cli-export/spec/src/zip/convertSpec.ts
  packages/akashic-cli-export/src/zip/apiUtil.ts
  packages/akashic-cli-export/src/zip/cli.ts
  packages/akashic-cli-export/src/zip/convert.ts
  packages/akashic-cli-export/src/zip/exportZip.ts
Labels: enhancement

#1224 feat(export): convert character encoding to UTF-8
  packages/akashic-cli-export/package-lock.json
  packages/akashic-cli-export/package.json
  packages/akashic-cli-export/spec/fixtures/simple_game_using_non_utf8/assets/euc-jp.txt
  packages/akashic-cli-export/spec/fixtures/simple_game_using_non_utf8/game.json
  packages/akashic-cli-export/spec/fixtures/simple_game_using_non_utf8/package.json
  packages/akashic-cli-export/spec/fixtures/simple_game_using_non_utf8/script/foo.js
  packages/akashic-cli-export/spec/fixtures/simple_game_using_non_utf8/script/main.js
  packages/akashic-cli-export/spec/fixtures/simple_game_using_non_utf8/text/sjis.txt
  packages/akashic-cli-export/spec/fixtures/simple_game_using_non_utf8/text/utf8.txt
  packages/akashic-cli-export/spec/src/zip/convertSpec.ts
  packages/akashic-cli-export/src/zip/GameConfigurationUtil.ts
  packages/akashic-cli-export/src/zip/convert.ts
Labels: enhancement

#1226 Change scan test to jest
  packages/akashic-cli-scan/.eslintrc.js
  packages/akashic-cli-scan/README.md
  packages/akashic-cli-scan/jest.config.js
  packages/akashic-cli-scan/package-lock.json
  packages/akashic-cli-scan/package.json
  packages/akashic-cli-scan/spec/support/jasmine.json
  packages/akashic-cli-scan/spec/tsconfig.json
  packages/akashic-cli-scan/src/__tests__/fixtures/dummy.aac
  packages/akashic-cli-scan/src/__tests__/fixtures/dummy.m4a
  packages/akashic-cli-scan/src/__tests__/fixtures/dummy.mp4
  packages/akashic-cli-scan/src/__tests__/fixtures/dummy.ogg
  packages/akashic-cli-scan/src/__tests__/fixtures/dummy1x1.png
  packages/akashic-cli-scan/src/__tests__/fixtures/dummy2.ogg
  packages/akashic-cli-scan/src/__tests__/fixtures/dummy_300x200.svg
  packages/akashic-cli-scan/src/__tests__/fixtures/dummy_300x200_subpx.svg
  packages/akashic-cli-scan/src/__tests__/fixtures/dummy_no_px.svg
  packages/akashic-cli-scan/src/__tests__/fixtures/dummy_no_size.svg
  packages/akashic-cli-scan/src/__tests__/src/AssetModuleSpec.ts
  packages/akashic-cli-scan/src/__tests__/src/getAudioDurationSpec.ts
  packages/akashic-cli-scan/src/__tests__/src/helpers/MockPromisedNpm.ts
  packages/akashic-cli-scan/src/__tests__/src/scanAssetSpec.ts
  packages/akashic-cli-scan/src/__tests__/src/scanNodeModulesSpec.ts
  packages/akashic-cli-scan/src/__tests__/src/scanUtilsSpec.ts
  packages/akashic-cli-scan/src/__tests__/tsconfig.json
  packages/akashic-cli-scan/src/scanAsset.ts
  packages/akashic-cli-scan/tsconfig.json
Labels: other

#1225 Remove atsumaru from serve
  packages/akashic-cli-serve/README.md
  packages/akashic-cli-serve/src/client/atsumaru/RPGAtsumaruApi.ts
  packages/akashic-cli-serve/src/client/atsumaru/ScoreboardData.ts
  packages/akashic-cli-serve/src/client/atsumaru/ScreenshotModalResults.ts
  packages/akashic-cli-serve/src/client/atsumaru/SelfInformation.ts
  packages/akashic-cli-serve/src/client/atsumaru/TweetSettings.ts
  packages/akashic-cli-serve/src/client/atsumaru/UserIdName.ts
  packages/akashic-cli-serve/src/client/atsumaru/UserInformation.ts
  packages/akashic-cli-serve/src/client/common/createSessionParameter.ts
  packages/akashic-cli-serve/src/client/operator/DevtoolOperator.ts
  packages/akashic-cli-serve/src/client/operator/Operator.ts
  packages/akashic-cli-serve/src/client/store/DevtoolUiStore.ts
  packages/akashic-cli-serve/src/client/view/App.tsx
  packages/akashic-cli-serve/src/client/view/container/DevtoolContainer.tsx
  packages/akashic-cli-serve/src/client/view/container/ToolbarContainer.tsx
  packages/akashic-cli-serve/src/client/view/molecule/AtsumaruDevtool.tsx
  packages/akashic-cli-serve/src/client/view/molecule/NiconicoDevtool.tsx
  packages/akashic-cli-serve/src/client/view/organism/Devtool.tsx
  packages/akashic-cli-serve/src/client/view/stories/Devtool.stories.tsx
  packages/akashic-cli-serve/src/common/targetServiceUtil.ts
  packages/akashic-cli-serve/src/server/index.ts
Labels: other

#1229 Fix scan bug on windows
  packages/akashic-cli-commons/src/NodeModules.ts
  packages/akashic-cli-export/package-lock.json
  packages/akashic-cli-export/package.json
Labels: bug
