Repository akashic-games/akashic-cli, pull requests merged in 2023-05, with the labels that each got.

#1234 chore(init): use unzipper@0.10.11
  packages/akashic-cli-init/package.json
Labels: bug

#1231 feat(serve): warn if message event size is too large
  packages/akashic-cli-commons/spec/src/asHumanReadableSpec.ts
  packages/akashic-cli-commons/src/asHumanReadable.ts
  packages/akashic-cli-commons/src/index.ts
  packages/akashic-cli-serve/src/client/api/Subscriber.ts
  packages/akashic-cli-serve/src/client/store/PlayStore.ts
  packages/akashic-cli-serve/src/client/store/Store.ts
  packages/akashic-cli-serve/src/common/MsgpackParser.ts
  packages/akashic-cli-serve/src/common/types/TestbedEvent.ts
Labels: enhancement

#1233 feat(export): output warning when exporting too large size
  packages/akashic-cli-commons/spec/src/UtilSpec.ts
  packages/akashic-cli-commons/src/Util.ts
  packages/akashic-cli-export/src/zip/constants.ts
  packages/akashic-cli-export/src/zip/convert.ts
Labels: enhancement

#1236 Revert "Update dependency engine.io to 6.4.2 [SECURITY]"
  packages/akashic-cli-export/package-lock.json
  packages/akashic-cli-lib-manage/package-lock.json
  packages/akashic-cli-scan/package-lock.json
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
Labels: bug

#1232 Remove atsumaru option in export html
  packages/akashic-cli-commons/src/CliConfig/CliConfigExportHtml.ts
  packages/akashic-cli-commons/src/ServiceType.ts
  packages/akashic-cli-export/spec/src/html/exportAtsumaruSpec.ts
  packages/akashic-cli-export/spec/src/html/exportHTMLSpec.ts
  packages/akashic-cli-export/src/html/cli.ts
  packages/akashic-cli-export/src/html/convertBundle.ts
  packages/akashic-cli-export/src/html/convertNoBundle.ts
  packages/akashic-cli-export/src/html/convertUtil.ts
  packages/akashic-cli-export/src/html/exportAtsumaru.ts
  packages/akashic-cli-export/src/html/exportHTML.ts
  packages/akashic-cli-export/src/zip/cli.ts
Labels: other

#1238 feat(init): template.json の exclude をサポート
  packages/akashic-cli-init/README.md
  packages/akashic-cli-init/jest.config.js
  packages/akashic-cli-init/package-lock.json
  packages/akashic-cli-init/package.json
  packages/akashic-cli-init/src/__tests__/TemplateConfigSpec.ts
  packages/akashic-cli-init/src/__tests__/cloneTemplateSpec.ts
  packages/akashic-cli-init/src/init/TemplateConfig.ts
  packages/akashic-cli-init/src/init/cloneTemplate.ts
  packages/akashic-cli-init/src/init/init.ts
  packages/akashic-cli-init/template-spec.md
  packages/akashic-cli-init/tsconfig.json
Labels: enhancement

#1240 Fix tests involving NodeModules#extractModuleMainInfo
  packages/akashic-cli-commons/spec/src/NodeModulesSpec.ts
  packages/akashic-cli-commons/src/NodeModules.ts
  packages/akashic-cli-commons/src/Util.ts
  packages/akashic-cli-export/src/html/cli.ts
  packages/akashic-cli-lib-manage/spec/src/install/installSpec.ts
  packages/akashic-cli-lib-manage/spec/src/uninstall/uninstallSpec.ts
  packages/akashic-cli-scan/src/__tests__/src/scanNodeModulesSpec.ts
Labels: bug
