Repository akashic-games/akashic-cli, pull requests merged in 2023-03, with the labels that each got.

#1211 chore(deps): update & follow headless-driver@2.6.3
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/package.json
  packages/akashic-cli-serve/src/server/tsconfig.json
Labels: dependencies

#1212 Fix scriptAsset update for watch option in serve
  packages/akashic-cli-serve/src/server/controller/ScriptAssetController.ts
Labels: bug

#1214 【akashic-cli-export】内部コンポーネントの更新(engineFiles@3.6.7, engineFiles@2.2.2, engineFiles@1.2.1)
  packages/akashic-cli-export/src/template/engineFilesVersion.json
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_6_2.js
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_6_7.js
Labels: enhancement

#1217 fix(serve): fix lost join in -s nicolive mode
  packages/akashic-cli-serve/package-lock.json
  packages/akashic-cli-serve/spec/server/SocketIOAMFlowManagerSpec.js
  packages/akashic-cli-serve/src/client/api/ApiClient.ts
  packages/akashic-cli-serve/src/client/operator/Operator.ts
  packages/akashic-cli-serve/src/client/store/PlayStore.ts
  packages/akashic-cli-serve/src/common/targetServiceUtil.ts
  packages/akashic-cli-serve/src/common/types/TestbedEvent.ts
  packages/akashic-cli-serve/src/server/controller/PlayController.ts
  packages/akashic-cli-serve/src/server/domain/PlayStore.ts
  packages/akashic-cli-serve/src/server/domain/RunnerStore.ts
  packages/akashic-cli-serve/src/server/index.ts
Labels: bug
