Repository akashic-games/akashic-cli, pull requests merged in 2023-01, with the labels that each got.

#1191 chore(serve): ゲームコンテンツ読み込み時のエラーを表示
  packages/akashic-cli-serve/src/client/akashic/GameViewManager.ts
Labels: bug

#1189 Mod local sendEvent in serve
  packages/akashic-cli-serve/src/client/akashic/AkashicGameViewWeb.d.ts
  packages/akashic-cli-serve/src/client/akashic/ServeGameContent.ts
  packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
Labels: other

#1200 【akashic-cli-export】内部コンポーネントの更新(engineFiles@3.6.2, engineFiles@2.2.2, engineFiles@1.2.1)
  packages/akashic-cli-export/src/template/engineFilesVersion.json
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_6_0.js
  packages/akashic-cli-export/src/template/template-export-html-v3/js/engineFilesV3_6_2.js
Labels: enhancement

#1202 Fix bug in experimental-open option
  packages/akashic-cli-serve/src/client/operator/PlayOperator.ts
Labels: bug
